BANG_DICT = {
    "!allegro": "Allegro",
    "!cakebook": "CakePHP Cookbook",
    "!animeka": "Animeka",
    "!webcams": "webcams.travel",
    "!ipernity": "Ipernity",
    "!trademe": "TradeMe",
    "!anidb": "aniDB",
    "!nuget": "nuget gallery",
    "!pgp": "MIT PGP Public Key Server Lookup",
    "!endthelie": "End the Lie",
    "!fuzz": "FuzzFind",
    "!slate": "Slate",
    "!wikipedia": "Wikipedia",
    "!wsjmw": "http://www.marketwatch.com/",
    "!wosn": "webOS Nation",
    "!cbsnews": "CBSNews",
    "!wosi": "WebOS Internals",
    "!emy": "ebay.com.my",
    "!searchforphp": "SearchForPHP",
    "!emc": "electronic medicines compendium",
    "!bondfaro": "Bondfaro",
    "!gpt": "Google PT",
    "!gps": "Google Product Search",
    "!sas": "SAS",
    "!gamesradar": "GamesRadar",
    "!qme": "quickmeme",
    "!espacenet": "Espacenet",
    "!twn": "The Weather Network",
    "!uscript": "Unity Script Reference",
    "!engadget": "Engadget",
    "!dvdfr": "DVDFr",
    "!najdi": "Najdi.si",
    "!issuu": "Issuu.com",
    "!ocal": "Open Clip Art Library",
    "!cooks": "Cooks.com",
    "!vmkb": "VMware Knowledge Base",
    "!wowarmoryeu": "WOW Armory EU",
    "!scifi": "Worlds Without End",
    "!vgg": "viagogo",
    "!everymac": "EveryMac.com",
    "!vgd": "v.gd",
    "!heise": "www.heise.de",
    "!validate": "W3C Validator",
    "!movielike": "Movielike",
    "!allelec": "All Electronics",
    "!n": "Google News",
    "!veoh": "Veoh",
    "!m": "Google Maps",
    "!videosift": "Videosift",
    "!i": "Google Images",
    "!g": "Google",
    "!heinzelnisse": "Heinzelnisse",
    "!e": "eBay",
    "!b": "Bing",
    "!price": "Amazon.com",
    "!a": "Amazon.com",
    "!isohunt": "ISOHunt",
    "!unscatter": "Unscatter.com",
    "!btdigg": "BtDigg",
    "!vin": "Decode This!",
    "!v": "YouTube",
    "!ter": "TYPO3 Extension Repository",
    "!t": "Thesaurus.com",
    "!r": "Reddit",
    "!s": "startpage.com",
    "!nico": "Nico Nico Douga",
    "!q": "Quora",
    "!perseus": "Perseus Digital Library",
    "!cache": "Google Cache",
    "!ontrac": "OnTrac",
    "!powiki": "Pokemon Online Wiki",
    "!lyricswiki": "LyricWiki",
    "!killerstartups": "killerstartups.com",
    "!eurogamer": "Eurogamer.net",
    "!glocal": "Google Local",
    "!arte": "http://arte.tv",
    "!cpdl": "Choral Public Domain Library",
    "!gisoff": "Google Images Safe Off",
    "!ip": "WhatIsMyIPAddress.com",
    "!nasa": "nasa",
    "!conj": "Le Conjugueur",
    "!nautiljon": "Nautiljon",
    "!cpp": "Cplusplus.com",
    "!amfr": "Amazon.fr",
    "!boardman": "Boardman Perspective",
    "!weheartit": "We Heart It",
    "!tweakers": "Tweakers.net",
    "!5": "Fiverr",
    "!jdk": "Java Docs",
    "!lp": "Launchpad",
    "!gamezebo": "Gamezebo",
    "!fenopy": "Fenopy",
    "!lv": "Livermore library",
    "!inab": "INeedaBargain.com",
    "!oxl": "Oxford Advanced Learner Dictionary",
    "!tuaw": "The Unofficial Apple Weblog TUAW",
    "!lavva": "Lavva",
    "!lh": "Lifehacker",
    "!lj": "LiveJournal",
    "!lm": "LiveMixtapes",
    "!ll": "LiveLeak",
    "!gamesandgeeks": "Games and Geeks",
    "!cnrtlm": "Centre National de Ressources Textuelles et Lexicales",
    "!nes": "Nationalencyklopedin",
    "!cnrtls": "Centre National de Ressources Textuelles et Lexicales",
    "!hackaday": "HackADay",
    "!cake2": "Cakephp 2 Api",
    "!wref": "Wordreference en->fr",
    "!devapple": "Apple Developer",
    "!alternate": "Alternate",
    "!wren": "WordReference",
    "!icon": "IconFinder",
    "!wiktionary": "Wiktionary",
    "!wres": "Wordreference",
    "!toppreise": "Toppreise.ch",
    "!catholic": "Catholic Answers",
    "!fcs": "Fulton County Schools",
    "!nationalgeographic": "National Geographic",
    "!opensuse": "OpenSUSE",
    "!vandale": "Van Dale",
    "!gnde": "Google News Germany",
    "!gorp": "Gorp",
    "!codeweavers": "Codeweavers Crossover application database",
    "!oolone": "Oolone",
    "!siteslike": "siteslike",
    "!ao3": "Archive of Our Own",
    "!wunderground": "Weather Underground",
    "!180": "180.no",
    "!golem": "Golem.de",
    "!emusic": "eMusic",
    "!fluidinfo": "fluidinfo.com",
    "!shopwiki": "Shopwiki",
    "!jvcom": "jeuxvideo.com",
    "!gplusp": "Google Plus",
    "!xdaf": "XDA-Developers Forum",
    "!abbuc": "Abbuc e.V.",
    "!lingvo": "Lingvo",
    "!yify": "YIFY Torrents",
    "!player": "Player FM",
    "!hecf": "Hazme El Chingado Favor",
    "!highrec": "HighRec",
    "!allbibles": "Online Parallel Bible",
    "!lgw": "libregamewiki",
    "!bwc": "Belfry Web Comics",
    "!hudku": "International Yellow Pages",
    "!ebaysg": "ebay.com.sg",
    "!mpgde": "Max Planck Society",
    "!cean": "CEAN",
    "!lgc": "legeekcafe.com",
    "!blogtalkradio": "BlogTalkRadio",
    "!lmdtfy": "LMDDGTFY.CO.CC",
    "!crossword": "WordFun crossword solver",
    "!gaccess": "Google Accessible",
    "!gid": "Google ID",
    "!gie": "Google IE",
    "!tudou": "土豆网",
    "!gim": "Google Images",
    "!ebayes": "ebay ES",
    "!boost": "Boost.org",
    "!gik": "Google IL",
    "!git": "Git",
    "!nrcnext": "NRC Next",
    "!ebde": "ebay.de",
    "!newscomau": "News.com.au",
    "!gir": "Dear Computer Google Image Ripper SFW",
    "!gis": "Google Search by Image",
    "!sciencedaily": "Sciencedaily",
    "!exfm": "exfm",
    "!blackbookmag": "BlackBook",
    "!mineforum": "Minecraft Forums",
    "!yandex": "Yandex",
    "!optimot": "Optimot",
    "!pkgs": "Linux Packages Search",
    "!drugs": "Drugs",
    "!zyrv": "Zyrv.com",
    "!mamma": "Mamma",
    "!stockphotos": "iStockPhoto",
    "!lycos": "Lycos",
    "!clojuredocs": "Clojure Docs",
    "!foofind": "Foofind",
    "!chicagotribune": "The Chicago Tribune",
    "!roadandtrack": "Road & Track",
    "!msh": "Jaen",
    "!nzbmatrix": "NzbMatrix",
    "!wowbattlenet": "BattleNet",
    "!trulia": "Trulia",
    "!okf": "otrkeyfinder",
    "!msq": "Morningstar Quote",
    "!gblast": "Gigablast ",
    "!bigfish": "Big Fish Games",
    "!eeggs": "Easter Eggs",
    "!mspa": "MS Paint Adventures Wiki",
    "!bay12": "Bay12Games",
    "!sba": "SBA",
    "!openradar": "OpenRadar",
    "!pcworld": "Pcworld",
    "!kotakuau": "KotakuAus",
    "!43things": "43Things",
    "!ixquickvideos": "Ixquick videos",
    "!naturespic": "Nature's Pic Images",
    "!xda": "XDA-Developers Forum",
    "!exif": "Jeffrey's Exif Viewer",
    "!animenewsnetwork": "Anime News Network",
    "!stock": "Google Finance",
    "!aukro": "Aukro",
    "!spi": "Startpage Images",
    "!pc": "ProCog",
    "!hoogle": "Hoogle",
    "!moviepilot": "Moviepilot DE",
    "!youtube": "YouTube",
    "!earth911": "Earth911.com",
    "!spr": "SitePoint Reference",
    "!lurk": "Lurkmoar",
    "!ilyax": "ilyax iblox is my blox",
    "!hadoop": "Search-Hadoop",
    "!xep": "XMPP Extension Protocols",
    "!animelyrics": "AnimeLyrics",
    "!tv2": "TV2",
    "!sslife": "Skyscraperlife",
    "!subreddit": "Reddit Subreddits",
    "!ytl": "YouTube - long",
    "!kerodicas": "KeroDicas",
    "!submarino": "Submarino",
    "!soso": "Soso",
    "!worldofspectrum": "World of Spectrum",
    "!nullege": "Nullege",
    "!emacs": "EmacsWiki",
    "!013": "0l3.de",
    "!filefacts": "Filefacts",
    "!carmag": "CarMagazine.co.uk",
    "!awesomecow": "Awesome Cow",
    "!wink": "Wink",
    "!next": "Next-Episode.net",
    "!winc": "Wikimedia Incubator",
    "!perldoc": "Perldoc.perl.org",
    "!wattpad": "Wattpad",
    "!3tailer": "3tailer",
    "!rfaces": "alltheragefaces",
    "!orthonet": "orthonet",
    "!ci": "Codeigniter User Guide",
    "!diigo": "Diigo",
    "!luaforge": "LuaForge",
    "!cf": "ColdFusion Docs",
    "!upackages": "Ubuntu Packages",
    "!cc": "CreativeCommons.org",
    "!wnl": "Wikipedia NL",
    "!wno": "Wikipedia NO",
    "!wnn": "Wikipedia Nynorsk",
    "!scala": "Scala ",
    "!geoip": "GeoIpTool",
    "!epl": "ebay.pl",
    "!investopedia": "Investopedia",
    "!vndb": "VNDB",
    "!worldcat": "WorldCat.org",
    "!shareware": "Download.com",
    "!gridcalendar": "GriCal",
    "!last.fm": "Last.fm",
    "!moo": "mooTools Docs",
    "!eph": "ebay.ph",
    "!thalia": "Thalia",
    "!mpny": "MenuPages",
    "!onion": "The Onion",
    "!ade": "Amazon.de",
    "!w3schools": "W3Schools.com",
    "!latex": "LaTeX Code",
    "!avax": "AvaxHome",
    "!merriamwebster": "Merriam-Webster",
    "!epg": "epguides.com",
    "!btmon": "BitTorrentMonster",
    "!ftp": "Mamont",
    "!nvd": "National Vulnerability Database",
    "!hatbuzz": "hatbuzz",
    "!wpl": "Wikipedia PL",
    "!libris": "Libris",
    "!cake2book": "Cakephp 2 Book",
    "!googlemaps": "Google Maps",
    "!pplware": "Pplware",
    "!ling": "Ling.pl",
    "!wykop": "Wykop",
    "!lyrics": "Lyric Wiki",
    "!jetwick": "Jetwick",
    "!cinemagay": "CinemaGay",
    "!d": "The Free Dictionary",
    "!help": "DuckDuckGo Help",
    "!leos": "LEO Dictionary Spanish",
    "!leor": "LEO Dictionary Russian",
    "!hack": "duckduckhack",
    "!leoi": "LEO Dictionary Italian",
    "!leof": "LEO Dictionary French",
    "!whois": "DomainTools.com",
    "!ted": "TED",
    "!leoc": "LEO Dictionary Chinese",
    "!wowpedia": "Wowpedia",
    "!mcanime": "MCAnime.net Beta",
    "!liquidation": "http://www.liquidation.com",
    "!gde": "Google DE",
    "!gdk": "Google DK",
    "!bigstock": "Bigstock",
    "!kindleuk": "Amazon UK Kindle",
    "!launchpad": "LaunchPad",
    "!gtranslate": "Google Translate",
    "!prisjakt": "Prisjakt",
    "!gdt": "Grand Dictionnaire Terminologique",
    "!vim": "Vim.org",
    "!ebayph": "ebay.ph",
    "!wieowie": "Wieowie",
    "!ebaypl": "ebay.pl",
    "!mootools": "mooTools Docs",
    "!here": "Here.net formerly Nokia Maps",
    "!ebes": "ebay ES",
    "!chefkoch": "Chefkoch",
    "!nounproject": "NounProject",
    "!food": "Food.com",
    "!w": "Wikipedia",
    "!gjp": "Google JP",
    "!pxb": "Pixabay",
    "!globeandmail": "The Globe And Mail",
    "!tokyotosho": "Tokyotosho",
    "!gittigidiyor": "GittiGidiyor",
    "!gpat": "Google Patents",
    "!acro": "Acronyms",
    "!foursquare": "foursquare",
    "!ohnorobot": "Oh No Robot",
    "!scaruffi": "Scaruffi",
    "!icecast": "Icecast Directory",
    "!gsub": "Greek Subtitles Project",
    "!glyde": "Glyde",
    "!everyclick": "Every Click",
    "!gsuk": "Google Shopping UK",
    "!musicme": "MusicMe",
    "!folha": "Folha de S. Paulo",
    "!chrome": "Chrome Extensions",
    "!gl": "google",
    "!cowboylyrics": "Cowboy Lyrics",
    "!bl": "DuckDuckGo Blinders",
    "!clseattle": "Craigslist",
    "!gpackages": "Gentoo Packages",
    "!h18": "http://hangar18.com.ar",
    "!giezhals": "Geizhals",
    "!html2txt": "Html2Txt",
    "!newsyc": "HNsearch",
    "!cnrtl": "Centre National des Ressources Textuelles et Lexicales",
    "!fren": "Wordreference",
    "!worm": "Wormbase",
    "!lspace": "L-Space",
    "!msmalware": "Microsoft malware encyclopedia",
    "!vogue": "Vogue.com",
    "!azfonts": "AZFonts",
    "!ebe": "ebay.be",
    "!web2py": "Web2Py",
    "!dhlgm": "DHL Global Mail",
    "!boardgamegeek": "BoardGameGeek",
    "!eventful": "Eventful",
    "!epinions": "Epinions",
    "!googletr": "Google Turkey",
    "!wotif": "Wotif",
    "!freecode": "FreshMeat.net",
    "!yeahway": "Yeah Way!",
    "!ips": "IPS",
    "!spstory": "cultura",
    "!reciva": "Reciva",
    "!ebayuk": "ebay.co.uk",
    "!howjsay": "HowJSay",
    "!wikthu": "Wiktionary hu",
    "!jinni": "Jinni",
    "!hotukdeals": "Hotukdeals",
    "!tld": "Gandi.net",
    "!dgg": "GG - dejure.org",
    "!leo": "LEO Dictionary",
    "!gog": "Good old games",
    "!god": "Guts of Darkness",
    "!ebbe": "ebay.be",
    "!espacoliberdade": "Espaço Liberdade",
    "!bce": "dict.bing.com.cn",
    "!lewrockwell": "LewRockwell.com",
    "!gov": "US Government Search",
    "!epfl": "EPFL",
    "!bcp": "Best Current Practices",
    "!citeseer": "CiteSeer",
    "!duo": "..duo dotdotduo",
    "!vggde": "viagogo.de",
    "!duc": "Duke University Catalog",
    "!ebca": "ebay.ca",
    "!ikso": "Ikso Kantaro",
    "!startpage": "StartPage",
    "!vimscripts": "Vim Scripts",
    "!xdcc": "XDCCFinder",
    "!gbugs": "Gentoo's Bugzilla",
    "!pollin": "Pollin Electronic",
    "!trfde": "transfermarkt.de",
    "!dman": "Debian Hypertext Man Pages",
    "!oopon": "Oopon",
    "!timestamp": "DuckDuckGo",
    "!gamefaqs": "GameFAQs.com",
    "!bookmine": "Gutenberg text content",
    "!nypost": "NYPost",
    "!indigo": "Indigo Books",
    "!forbes": "Forbes",
    "!compass": "Compass",
    "!dribbble": "dribbble",
    "!miniclip": "Miniclip",
    "!bsocial": "Bing Social",
    "!lololyrics": "Lololyrics",
    "!gplay": "Google Play Store",
    "!zapaday": "Zapaday",
    "!apolloduck": "Apollo Duck",
    "!idealode": "Idealo",
    "!scipy": "SciPy",
    "!munju": "Munju",
    "!evirttit": "Estante Virtual by title",
    "!isup": "Is Up?",
    "!catalinstefan": "http://android.catalinstefan.com/",
    "!shoutcast": "Shoutcast Streaming Internet Radio",
    "!geocaching": "Geocaching.com",
    "!bbapps": "BlackBerry App World",
    "!meteociel": "Meteociel",
    "!canistream": "Can I Stream It?",
    "!pagine": "Pagine Gialle",
    "!wadoku": "WaDoKu",
    "!spinoza": "Spinoza",
    "!gmob": "Google mobile site viewer",
    "!pep": "Python PEP",
    "!ebayin": "ebay.in",
    "!yellownz": "Yellow NZ",
    "!shopzilla": "Shopzilla",
    "!ebayie": "ebay.ie",
    "!coldfusion": "ColdFusion Docs",
    "!gtabs": "UltimateGuitar.com",
    "!dtc": "DansTonChat",
    "!java6": "Java6 Docs",
    "!java7": "Java7 Docs",
    "!kippt": "Kippt",
    "!taobao": "Taobao",
    "!stackoverflow": "StackOverflow",
    "!anandtech": "Anandtech",
    "!mendeley": "Mendeley",
    "!python3": "Python3 Docs",
    "!jed": "Joomla ",
    "!tradera": "Tradera",
    "!texdoc": "Texdoc",
    "!mv": "Myvideo",
    "!mw": "Merriam-Webster",
    "!tent": "Skate",
    "!ms": "Microsoft",
    "!mp": "MenuPages",
    "!mq": "MapQuest",
    "!angelhalowiki": "Angelhalo Wiki",
    "!bbcw": "BBC Weather",
    "!tanzil": "Tanzil",
    "!mb": "MusicBrainz",
    "!rosettacode": "RosettaCode.org",
    "!ma": "Memory Alpha",
    "!duckco": "The DuckDuckGo Community",
    "!ml": "Mercado Livre",
    "!mh": "The Monster Hunter Wiki",
    "!pbone": "RPM.pbone.net",
    "!wln": "WestlawNext",
    "!pronounce": "Dictionary.com",
    "!bestsimilarsites": "bestsimilarsites",
    "!cpandeps": "CPAN Dependencies Checker",
    "!huffingtonpost": "Huffington Post",
    "!apache": "Apache.org",
    "!mib": "Mibbit",
    "!gworkshop": "Games Workshop",
    "!kickstarter": "Kickstarter",
    "!rpggeek": "RPGGeek",
    "!hi5": "Hi5",
    "!gwiki": "Gentoo Wiki",
    "!groove": "Grooveshark",
    "!atom": "Atomurl ",
    "!biography": "Biography.com",
    "!uzg": "Uitzending Gemist",
    "!fhtml": "Fireburst HTML",
    "!jumpr": "Jump",
    "!lw": "LessWrong",
    "!adlibrisno": "AdLibris NO",
    "!komputeko": "Komputeko",
    "!csfd": "ČSFD",
    "!symbolhound": "Symbol Hound",
    "!cook": "Cooks.com",
    "!upcoming": "Upcoming",
    "!appledev": "Apple Developer",
    "!rateyourmusic": "Rate Your Music",
    "!jarvanacontent": "Jarvana",
    "!clojure": "Clojure Docs",
    "!mapp": "ACME Mapper 2.0",
    "!maps": "Google Maps",
    "!discovery": "Discovery.com",
    "!ibm": "IBM",
    "!enfr": "Wordreference",
    "!man7": "The Linux man-pages project",
    "!mamont": "Mamont",
    "!mathoverflow": "MathOverflow",
    "!dram": "Encyclopedia Dramatica",
    "!avclub": "A.V. Club",
    "!d20": "d20 SRD",
    "!cms": "Chicago Manual of Style",
    "!bulbapedia": "Bulbapedia",
    "!subsearch": "Subsearch",
    "!majorsbooks": "Majors Books",
    "!creativecow": "Creative Cow Forums",
    "!ripestat": "RIPEstat",
    "!koreus": "Koreus",
    "!pixelp": "PixelProspector",
    "!li": "LinkedIn",
    "!nyt": "New York Times",
    "!myopera": "My Opera",
    "!gnfr": "Google News French",
    "!acm": "ACM Guide to Computing Literature",
    "!gallica.bnf": "Gallica BNF",
    "!willh": "The Will Will Web",
    "!slwiki": "Second Life Wiki",
    "!askapatient": "AskaPatient.com",
    "!sierrasoftworks": "Sierra Softworks",
    "!gamespot": "GameSpot",
    "!dhnet": "La Dernière Heure",
    "!watchtower": "Watchtower Online Library",
    "!yjp": "Yahoo! Japan",
    "!skyrock": "SkyRock",
    "!dell": "Dell",
    "!tabs": "UltimateGuitar.com",
    "!dlpo": "Dicionário Priberam da Língua Portuguesa",
    "!skroutz": "skroutz",
    "!flickriver": "Flickriver",
    "!bbc": "BBC.co.uk",
    "!ghk": "Google HK",
    "!flickpeek": "FlickPeek",
    "!iarchive": "archive.org",
    "!ebayde": "ebay.de",
    "!sonicretro": "Sonic Retro / Sega Retro",
    "!openbook": "OpenBook",
    "!qobuz": "Qobuz",
    "!ebch": "ebay.ch",
    "!bbt": "BakaBT",
    "!sulit": "Sulit",
    "!psulib": "Penn State Library",
    "!rfc": "tools.ietf.org",
    "!gcsebitesize": "BBC GCSE Bitesize",
    "!onelook": "OneLook",
    "!nyaa": "Nyaa Torrents",
    "!swdb": "The Spaghetti Western Database",
    "!fxr": "FreeBSD Cross Reference",
    "!arcgis": "ArcGIS Online",
    "!neto": "Netophonix",
    "!gus": "Google US",
    "!cfp": "WikiCFP",
    "!grave": "Find A Grave",
    "!dbgb": "BGB - dejure.org",
    "!rps": "Rock, Paper, Shotgun",
    "!ordfr": "Ord.se FR",
    "!amazonde": "Amazon",
    "!mvnrepository": "MVNRepository",
    "!nestuk": "Nestoria UK",
    "!reuq": "Stock Quotes & Company News | Reuters.com",
    "!dhgate": "DHGate",
    "!accuweather": "AccuWeather",
    "!vgguk": "viagogo.co.uk",
    "!gocomics": "GoComics",
    "!bimages": "Bing Images",
    "!rpm": "RPMfind.net",
    "!legal": "Google Scholar - Legal Opinion Section",
    "!cnet": "CNET",
    "!workcircle": "Workcircle",
    "!khanacademy": "Khan academy",
    "!search.refertus": "search.refertus",
    "!startrek": "Memory Alpha",
    "!lovefilm": "lovefilm.com",
    "!priberam": "Priberam",
    "!deezer": "Deezer",
    "!bloomberg": "Bloomberg",
    "!wikimapia": "Wikimapia",
    "!qrobe": "qrobe.it",
    "!douban": "Douban",
    "!suntimes": "SunTimes",
    "!ccr": "Chakra Community Repository",
    "!yjisho": "Yahoo Jisho",
    "!indeed": "Indeed",
    "!amglobal": "Amazon GLOBAL",
    "!yimages": "Yahoo! Images",
    "!techdirt": "TechDirt",
    "!mathse": "Mathematics - Stack Exchange",
    "!imb": "imbiomed",
    "!domainr": "Domainr",
    "!img": "Google Images",
    "!4chan": "FoOlz [4chan] Archives",
    "!kkbruce": "KingKong Bruce記事",
    "!derpibooru": "Derpibooru",
    "!writen": "Wordreference it->en",
    "!vogueuk": "Vogue.co.uk",
    "!proc": "Processing.org",
    "!bible": "BibleGateway",
    "!liquipedia": "Liquipedia2",
    "!pdf": "PDFs",
    "!gplus": "Google Plus",
    "!pdb": "RSCB Protein Data Bank",
    "!linkedin": "LinkedIn",
    "!acronyms": "Acronyms",
    "!dolu": "Dolu Sozluk",
    "!eventid": "EventID",
    "!mp3skull": "MP3Skull",
    "!bitsnoop": "BitSnoop",
    "!hypem": "The Hype Machine",
    "!sanakirja": "Sanakirja.org",
    "!blogs": "Google Blogs",
    "!4shared": "4shared",
    "!whiskyde": "whisky DE",
    "!amit": "Amazon.it",
    "!mercurynews": "Mercury News",
    "!miso": "http://gomiso.com/",
    "!mpph": "MenuPages",
    "!wallbase": "wallbase",
    "!chef": "Opscode Chef Wiki",
    "!makeuseof": "MakeUseOf",
    "!scritique": "SensCritique",
    "!veroot": "Veroot",
    "!lynxview": "Lynx Viewer Yellowpipe.com",
    "!charity": "Charity Navigator",
    "!wmc": "https://commons.wikimedia.org/",
    "!cnn": "CNN",
    "!asoiaf": "A Wiki of Ice and Fire",
    "!caniuse": "Can I use...",
    "!synonym": "Thesaurus.com",
    "!similar": "SimilarSites",
    "!pinboard": "Pinboard",
    "!redis": "Redis Command Reference",
    "!foodsubs": "Cook's Thesaurus",
    "!hrwiki": "Homestar Runner Wiki",
    "!howthingswork": "How Things Work",
    "!ubottu": "Ubottu.com",
    "!oid": "Search OID registry",
    "!azlyrics": "A-Z Lyrics",
    "!dailymed": "DailyMed",
    "!michaelis": "Michaelis - Portugues - English",
    "!mitvid": "MIT Video",
    "!api": "DuckDuckGo API",
    "!bigwords": "BigWords.com",
    "!ggroups": "Google Groups",
    "!nvidia": "Nvidia",
    "!mmnt": "Mamont",
    "!answers": "Answers.com",
    "!mash": "mashable",
    "!uesp": "The Unoffical Elder Scrolls pages",
    "!nfb": "National Film Board of Canada",
    "!mpsf": "MenuPages",
    "!dwds": "DWDS",
    "!jeopardy": "J! Archive",
    "!archlinux": "Archlinux Forums",
    "!shooter": "Shooter",
    "!fdo": "freedesktop.org",
    "!123p": "123people",
    "!zappos": "Zappos",
    "!gvpl": "Greater Victoria Public Library",
    "!fda": "FDA",
    "!wowarmory": "WOW Armory",
    "!musopen": "Musopen",
    "!qrdecode": "ZXing QR decode",
    "!dbasx": "DBA StackExchange",
    "!ann": "Anime News Network",
    "!kcommunity": "KDE Community Wiki",
    "!dfm": "definefor.me",
    "!htf": "HowtoForge",
    "!htg": "How-To Geek shortcut",
    "!dfw": "DwarfFortress Wiki",
    "!debianforums": "Debian Forums",
    "!gw2wiki": "Guild Wars 2 Wiki",
    "!politiken": "Politiken.dk",
    "!osalt": "osalt.com",
    "!principien": "Principien",
    "!texture": "Google Images",
    "!androidpit": "AndroidPit",
    "!imgur": "Imgur",
    "!focalprice": "Focalprice",
    "!blender": "Blender",
    "!yummly": "Yummly",
    "!lifehacker": "Lifehacker",
    "!allabolag": "Alla Bolag",
    "!goodreads": "GoodReads",
    "!senderbase": "SenderBase",
    "!utf8": "Unicode Character Search",
    "!yopmail": "YopMail",
    "!agdl": "The Annotated Grateful Dead Lyrics",
    "!opensusesoftware": "OpenSUSE Software Search",
    "!fefe": "Fefes Blog",
    "!sloanes": "Integer Sequences",
    "!govtrack": "govtrack.us",
    "!googleuk": "Google UK",
    "!trakt": "Trakt",
    "!palgn": "PALGN",
    "!wakoopa": "Wakoopa",
    "!sdict": "SpanishDict",
    "!fireburstvideos": "Videos - Fireburst",
    "!yanswers": "Yahoo! Answers",
    "!trello": "Trello",
    "!lds": "The Church of Jesus Christ of Latter-day Saints",
    "!cellartracker": "CellarTracker",
    "!ebuk": "ebay.co.uk",
    "!wiktit": "Wikizionario, il dizionario libero",
    "!thomas": "Thomas.loc.gov",
    "!login": "BugMeNot",
    "!dictcc": "dict.cc",
    "!wit": "Wikipedia IT",
    "!wiq": "WordIQ",
    "!cbc": "CBC News",
    "!imbd": "IMBD",
    "!techrights": "TechRights",
    "!songsterr": "Songsterr",
    "!trovaprezzi": "Trovaprezzi.it",
    "!extratorrent": "ExtraTorrent",
    "!amazonmp3": "Amazon MP3 Store",
    "!911s": "911 Tabs Songs",
    "!binsearch": "Binsearch",
    "!posters": "All Posters",
    "!rl": "Rapidlibrary",
    "!freebsd": "FreeBSD",
    "!baidu": "Baidu",
    "!rg": "Rap Genius",
    "!collegeconfidential": "CollegeConfidential Forums",
    "!tubafm": "Tuba FM",
    "!rb": "Redbubble",
    "!nintendolife": "Nintendo Life",
    "!domainsbot": "domainsbot.com",
    "!ynews": "Yahoo! News",
    "!whosampled": "who sampled",
    "!rt": "Rotten Tomatoes",
    "!plot": "FooPlot",
    "!okgeek": "Okay Geek",
    "!iusethis": "iusethis.com",
    "!dhl": "DHL",
    "!numerama": "Numerama",
    "!sproducts": "Sproducts",
    "!pylons": "Pylons Docs",
    "!wordpress": "WordPress.org",
    "!wikisum": "Wiki Summaries",
    "!teamliquid": "Teamliquid",
    "!debbug": "Debian Bugs",
    "!pcmag": "Pcmag",
    "!tureng": "Tureng Dictionary",
    "!nbd": "Norwegian Bokmål Dictionary",
    "!nba": "NBA.com",
    "!dll": "DLL-files.com",
    "!sloganmaker": "SloganMaker",
    "!chip": "CHIP Online",
    "!sphp": "SearchForPHP",
    "!shopathome": "ShopAtHome.com",
    "!perlmonks": "PerlMonks.org",
    "!ajc": "AJC.com",
    "!ajb": "Acha Jogo Barato",
    "!teketen": "Teketen",
    "!foodnetwork": "Food Network",
    "!git-scm": "Git",
    "!elen": "Google translate el-en",
    "!bakabt": "BakaBT",
    "!subs": "addic7ed",
    "!compfight": "Compfight",
    "!urlquery": "Urlquery",
    "!qype": "Qype",
    "!crunchyroll": "CrunchyRoll",
    "!scoop": "Scoop.it",
    "!regex": "Regular Expression Library",
    "!tatoeba": "Tatoeba",
    "!wikivs": "WikiVS",
    "!lotrow": "LOTRO-Wiki",
    "!cashback": "Sunshine Rewards",
    "!vemo": "Vemo.it forniture alberghiere",
    "!racket": "Racket",
    "!capost": "Canada Post",
    "!geocache": "Geocaching.com",
    "!mcpan": "MetaCPAN",
    "!zavvi": "Zavvi",
    "!mitocw": "MIT OpenCourseWare",
    "!son2teuf": "Son2Teuf",
    "!searchyc": "HNsearch",
    "!clipstijl": "Clipstijl",
    "!laser": "LaserShip",
    "!hgnc": "HUGO Gene Nomenclature Committee HGNC",
    "!musiciansfriend": "Musician's Friend",
    "!macupdate": "MacUpdate",
    "!chords": "UltimateGuitar.com",
    "!patternry": "Patternry",
    "!gbooks": "Google Books",
    "!iwant": "iWantMyName",
    "!yatr": "Yandex Turkiye",
    "!btn": "Broadcasthe.net",
    "!activeden": "ActiveDen",
    "!ebit": "ebay.it",
    "!gfc": "greatfirewallofchina.org",
    "!imagenet": "ImageNet",
    "!newsday": "NewsDay.com",
    "!gfi": "Google FI",
    "!findlaw": "FindLaw",
    "!nciku": "Nciku.com",
    "!rhyme": "RhymeZone",
    "!ebie": "ebay.ie",
    "!gfr": "Google FR",
    "!ebin": "ebay.in",
    "!ii": "Ixquick Images",
    "!huffpost": "Huffington Post",
    "!nzbs": "nzbs.org",
    "!bing": "Bing",
    "!susebug": "openSUSE Bugzilla",
    "!musicbrainz": "MusicBrainz",
    "!date": "Date Sort",
    "!im": "Google Images",
    "!twinpedia": "Twinpedia",
    "!passmark": "passmark.com",
    "!magma": "MagmaWiki",
    "!skepticsbible": "Skeptic's Bible",
    "!sunpatch": "WeSunSolve",
    "!lyricsmania": "Lyrics Mania",
    "!macworld": "Macworld",
    "!mskb": "Microsoft Knowledge Base",
    "!osnews": "OSNews",
    "!scope.dk": "scope.dk",
    "!yegg": "Gabriel Weinberg's Blog",
    "!mvn": "Maven Central",
    "!facebook": "Facebook",
    "!wtpt": "Wiktionary portuguese",
    "!dipadova": "Perpetual DiPadova",
    "!mhwiki": "The Monster Hunter Wiki",
    "!answer": "Yahoo! Answers",
    "!mathworks": "Matlab File Exchange",
    "!captaincrawl": "CaptainCrawl",
    "!indiamart": "IndiaMART",
    "!wordnet": "WordNet",
    "!seb": "Sebsauvage",
    "!sec": "SEC.gov",
    "!tsa": "TechSupportAlert.com",
    "!photodune": "PhotoDune",
    "!appcel": "Appcelerator API Docs",
    "!zbmath": "Zentralblatt MATH Database",
    "!esg": "ebay.com.sg",
    "!cricinfo": "Cricinfo",
    "!sep": "Stanford Encyclopedia of Philosophy",
    "!seq": "The Online Encyclopedia Of Integer Sequences",
    "!istockphoto": "iStockPhoto",
    "!tsr": "The Student Room",
    "!xkcdn": "XKCD Number",
    "!ihep": "InspireHEP",
    "!grepcode": "GrepCode.com",
    "!alto": "AlternativeTo",
    "!psimplified": "Programming Simplified",
    "!lpbug": "Launchpad Bugs",
    "!kapi": "KDE API Reference",
    "!newsnow": "News Now",
    "!crunchbase": "CrunchBase",
    "!gmap": "Google Maps",
    "!dailymotion": "DailyMotion",
    "!themag": "The Mag",
    "!prpm": "Pusat Rujukan Persuratan Melayu",
    "!codeplex": "Codeplex",
    "!kbugs": "KDE Bugs",
    "!7digital": "7digital",
    "!dpdt": "DPD Online Tracking",
    "!pubmed": "PubMed",
    "!mednar": "Mednar",
    "!snopes": "Snopes.com",
    "!uglifyjs": "UglifyJS",
    "!eqd": "Equestria Daily",
    "!tmd": "torrentsmd.com",
    "!wrenit": "Wordreference en->it",
    "!dictionary": "Dictionary.com",
    "!osub": "OpenSubtitles.org",
    "!glu": "Google Luxembourg",
    "!scienceblogs": "Science Blogs",
    "!usa": "Search.USA.gov",
    "!usc": "Ubuntu Software Center",
    "!reddit": "reddit",
    "!pictures": "Google Images",
    "!songmeanings": "SongMeanings",
    "!wikt": "Wiktionary",
    "!kasperskymal": "Securelist Malware info",
    "!news": "Google News",
    "!slackbuilds": "Slackbuilds",
    "!torwiki": "Torproject Wiki",
    "!newegg": "Newegg",
    "!etree": "Live Music Archive",
    "!mathematica": "Mathematica Documentation Center",
    "!nlab": "nLab",
    "!newsarchive": "Google News Archive",
    "!rails": "Rails Docs",
    "!gettyimages": "Getty Images",
    "!wiki": "Wikipedia",
    "!serebii": "Serebii",
    "!tvtropes": "TV Tropes",
    "!cheapassgamer": "Cheap Ass Gamer",
    "!drupalcontrib": "DrupalContrib",
    "!rutube": "RuTube",
    "!inspire": "Inspire HEP ",
    "!goosh": "Goosh",
    "!microcenter": "Micro Center",
    "!doi": "DOI.org",
    "!scrape": "Scrape Torrent",
    "!tiho": "TiHo-OPAC",
    "!myallsearch": "MyAllSearch",
    "!gramota": "gramota.ru",
    "!brightstorm": "Brightstorm",
    "!tcrf": "The Cutting Room Floor",
    "!lcc": "Let’s CC",
    "!nsr": "NationStates Region",
    "!ideas": "RePEc IDEAS",
    "!ilsole24ore": "Il Sole 24 Ore",
    "!/.j": "Slashdot Japan",
    "!verbomatic": "Verb-o-Matic",
    "!nsn": "NationStates Nation",
    "!forkd": "Forkd",
    "!ros": "ROS",
    "!ikeanl": "IKEA Nederland",
    "!techcrunch": "Techcrunch",
    "!crate": "Crate.io",
    "!movies": "movies.io",
    "!cwebstore": "Chrome Webstore",
    "!staticice": "Static Ice",
    "!fark": "Fark.com",
    "!cake": "CakePHP API",
    "!gtrends": "Google Trends",
    "!blackbook": "BlackBook",
    "!dblp": "DBLP",
    "!gtnl": "Google Translate to Dutch",
    "!ordbok": "Ordbok.no",
    "!parabola": "Parabola GNU/Linux",
    "!jarvanaclass": "www.jarvana.com",
    "!rapidonline": "Rapid Online",
    "!plan3t": "Plan3t.info",
    "!beatport": "Beatport",
    "!naver": "Naver",
    "!oreilly": "O'Reilly",
    "!zanran": "Zanran",
    "!fwiki": "Fortran Wiki",
    "!onimoto": "Onimoto.Com",
    "!purolator": "Purolator shipment tracking",
    "!br": "Baseball-Reference",
    "!apackages": "ArchLinux Packages",
    "!batlyrics": "Batlyrics",
    "!ebates": "Ebates",
    "!bkr": "Basketball Reference",
    "!qssl": "Qualys SSL Labs",
    "!vukajlija": "Vukajlija",
    "!/.": "Slashdot",
    "!dict.cc": "dict.cc",
    "!traceroute": "DomainTools.com",
    "!recipe": "Punchfork",
    "!ggr": "Google GR",
    "!gin": "Google IN",
    "!rockethub": "RocketHub",
    "!mercadolivre": "Mercado Livre",
    "!stex": "Stack Exchange",
    "!lastfm": "Last.fm",
    "!piratenwiki": "Wiki der Piratenpartei Deutschland",
    "!startribune": "The Star Tribune",
    "!gua": "Google UA",
    "!gaen": "Google Translate",
    "!iqdb": "iqdb",
    "!eat": "ebay.at",
    "!eau": "ebay.com.au",
    "!guk": "Google UK",
    "!inci": "incisozluk",
    "!wiggle": "www.wiggle.co.uk",
    "!yfinance": "Yahoo Finance",
    "!wimp": "wimp.com",
    "!verb": "Verb-o-Matic",
    "!dsv": "DSV SU",
    "!ebayau": "ebay.com.au",
    "!ebayat": "ebay.at",
    "!appshopper": "Appshopper",
    "!rym": "Rate Your Music",
    "!android": "Android Developers",
    "!indiegogo": "IndieGoGo",
    "!slang": "The Online Slang Dictionary",
    "!stackexchange": "stackexchange.com",
    "!zumi": "Mapy Zumi",
    "!wos": "World of Spectrum",
    "!dawanda": "DaWanda",
    "!vtkcd": "Visualization Toolkit VTK class documentation devel",
    "!anisearch": "aniSearch.de",
    "!imagery": "http://elzr.com/imagery/",
    "!djpackages": "Django Packages",
    "!radiotimes": "Radio Times",
    "!metalstorm": "Metal Storm",
    "!trl": "The Ring Lord",
    "!trademarks": "Trademarkia",
    "!orkut": "Orkut",
    "!recordclick": "www.recordclick.com",
    "!sfe": "Sparkfun Electronics",
    "!trz": "Torrentz",
    "!sfs": "stopforumspam.com",
    "!chakrawiki": "The Chakra Project Wiki",
    "!newark": "Newark",
    "!rei": "REI",
    "!gb": "Google Books",
    "!gdrive": "Google Drive",
    "!ge": "google.encypted.com",
    "!gf": "Google Finance",
    "!gg": "Google Groups",
    "!gh": "GitHub.com",
    "!gi": "Google Images",
    "!gj": "Google Japan",
    "!anyr": "DuckDuckGo",
    "!swagbucks": "Swagbucks",
    "!whitewater": "Whitewater Search Engine",
    "!gn": "Google News",
    "!gp": "Google Photos",
    "!gr": "Google Reader",
    "!gs": "Google Shopping",
    "!gt": "Google Translate",
    "!gv": "Google Video",
    "!gd": "Google Docs",
    "!thinkgeek": "ThinkGeek",
    "!tmdb": "TheMovieDB.org",
    "!siteduzero": "Site du Zéro",
    "!sf2": "Symfony Framework",
    "!gfaqs": "GameFAQS.com",
    "!coupons": "DealTaker",
    "!mogr": "moviegram",
    "!wikitravel": "Wikitravel",
    "!instructables": "Instructables",
    "!matlab": "Matlab documentation",
    "!ups": "UPS",
    "!imfdb": "Internet Movie Firearms Database",
    "!updown": "DownForEveryone?",
    "!drae": "Diccionario de la lengua española",
    "!emuparadise": "Emuparadise",
    "!bartlets": "Bartelby",
    "!exalead": "Exalead",
    "!nsprings": "North Springs Community",
    "!wdr": "webDevRefinery",
    "!tmbw": "This MIght Be a Wiki",
    "!gmane": "Gmane",
    "!wdt": "Wikidata",
    "!map": "Google Maps",
    "!fireburst": "Fireburst Web Search",
    "!freepascal": "Freepascal",
    "!rakuten": "Rakuten",
    "!wda": "Wikipedia DA",
    "!winfu": "WinFuture",
    "!man": "man.cx",
    "!wde": "Wikipedia DE",
    "!mac": "MAC Address",
    "!iplayer": "iPlayer",
    "!taringa": "Taringa!",
    "!p4k": "Pitchfork Media",
    "!pollstar": "Pollstar",
    "!princeton": "Princeton",
    "!slashdot": "Slashdot",
    "!jetslide": "Jetslide News Reader",
    "!wja": "Wikipedia JA",
    "!stationsweb": "Stationsweb",
    "!hs": "Honyaku Star",
    "!java4": "Java4 Docs",
    "!albumartdvd": "Albumart DVD",
    "!snake": "Just Snake",
    "!idioms": "The Free Dictionary",
    "!qr": "QR Code Search",
    "!nfl": "NFL.com",
    "!code": "Search Code",
    "!topsy": "Topsy",
    "!adlibrisdk": "AdLibris DK",
    "!qt": "Qt Reference Documentation",
    "!java5": "Java5 Docs",
    "!compete": "Compete",
    "!gentoowiki": "Gentoo Wiki",
    "!xgau": "Robert Christgau",
    "!powells": "Powells",
    "!weather": "WeatherBug",
    "!careerbuilder": "CareerBuilder",
    "!discogs": "Discogs",
    "!gizmodo": "Gizmodo",
    "!matlabfx": "Matlab File Exchange",
    "!tomshardware": "Tom's Hardware",
    "!historious": "Historious",
    "!lolpro": "LoL Pro",
    "!define": "The Free Dictionary",
    "!amjp": "Amazon.co.jp",
    "!hnsearch": "HNsearch",
    "!gopher": "Floodgap Gopher",
    "!qwiki": "Qwiki",
    "!hoepli": "Hoepli",
    "!camel": "CamelCamelCamel",
    "!nestde": "Nestoria Deutschland",
    "!mangafox": "Mangafox",
    "!g24": "Google Past 24h",
    "!appvv": "AppVV",
    "!smention": "Social Mention",
    "!thingiverse": "Thingiverse",
    "!csharp": "C# MSDN",
    "!crx": "Chrome Extension Repository",
    "!searchworks": "SearchWorks SULAIR",
    "!devonforum": "DEVONtechnologies Forum",
    "!randt": "Road & Track",
    "!wowwiki": "WoWWiki",
    "!oldcpan": "CPAN",
    "!habra": "habrahabr.ru",
    "!gphotos": "Google Photos",
    "!leboncoin": "Leboncoin.fr",
    "!msmvps": "MSMVPs.com",
    "!gm": "Google Maps",
    "!newsfr": "Google News France",
    "!bv": "Bing Videos",
    "!ww": "Whitewater Search Engine",
    "!bs": "Bing Shopping",
    "!sbo": "SlackBuilds.org",
    "!bn": "Barnes & Noble",
    "!bm": "bing maps",
    "!pecl": "PECL :: The PHP Extension Community Library",
    "!bi": "Bing Images",
    "!orthodoxwiki": "OrthodoxWiki",
    "!ebert": "RogerEbert.com",
    "!bd": "baidu",
    "!bc": "DuckDuckGo",
    "!bb": "Bitbucket",
    "!ba": "Beer Advocate",
    "!targeo": "Targeo",
    "!lyricwiki": "LyricWiki",
    "!ezydvd": "EzyDVD",
    "!wot": "Web of Trust",
    "!quizlet": "Quizlet",
    "!liquidpedia": "Liquidpedia",
    "!wog": "World of Gnome",
    "!yandexen": "Yandex english",
    "!target": "Target",
    "!mlb": "The official site of Major League Baseball",
    "!nethack": "NetHack Wiki",
    "!gcpan": "CPAN -> GREP",
    "!thefullwiki": "The Full Wiki",
    "!musikm": "Musik Meisinger Burghausen",
    "!wa": "WolframAlpha",
    "!tweet": "Tweet",
    "!newgrounds": "Newgrounds",
    "!fishpond": "Fishpond",
    "!summitpost": "SummitPost",
    "!debian": "Debian",
    "!cald": "Cambridge Advanced Learner's Dictionary",
    "!docs": "Scribd.com",
    "!websitedown": "Website Down",
    "!twitch": "TwitchTV",
    "!play": "Play.com",
    "!faucet": "Faucet.com",
    "!shopping": "Google Shopping",
    "!what": "What",
    "!firefox": "Firefox Add-ons",
    "!giga": "GIGABLAST",
    "!molw": "WebQC.org",
    "!bang": "DuckDuckGo",
    "!gch": "Google CH",
    "!sanalpazar": "Sanal Pazar",
    "!package": "PackageMapping",
    "!abcnews": "ABCNews",
    "!zapiks": "Zapiks",
    "!safe": "DDG Safesearch On",
    "!nds": "Nachdenkseiten",
    "!sparknotes": "SparkNotes",
    "!alc": "Eijiro on the web",
    "!ali": "Aliexpress",
    "!fbr": "Pro Basketball Reference",
    "!xbox": "Xbox",
    "!tumblr": "Tumblr",
    "!fatwallet": "FatWallet",
    "!meneame": "Menéame",
    "!comicvine": "Comic Vine",
    "!winehq": "WineHQ",
    "!baseballreference": "Baseball-Reference",
    "!boxoh": "Boxoh",
    "!criticker": "Criticker",
    "!gsmarena": "GSMArena",
    "!govimages": "US Government Image Search",
    "!gee": "Google EE",
    "!ncix": "NCIX.com",
    "!glatest": "Google Latest",
    "!freenode": "Freenode",
    "!datasheet": "AllDataSheet",
    "!buy": "Amazon.com",
    "!omim": "http://www.ncbi.nlm.nih.gov/omim",
    "!ges": "Google Spain",
    "!bibletools": "Bible Study Tools",
    "!kapaza": "Kapaza",
    "!behindsurname": "http://surnames.behindthename.com/",
    "!joystiq": "Joystiq",
    "!dlang": "D Programming Language",
    "!marmiton": "Marmiton",
    "!freshmeat": "FreshMeat.net",
    "!tex": "TeX Stack Exchange",
    "!fantasy": "fantasy.fr",
    "!bgp": "Hurricane Electrics Internet Services",
    "!vsg": "Value Stock Guide",
    "!ebfr": "ebay.fr",
    "!bgg": "BoardGameGeek",
    "!webstats": "webstatsdomain",
    "!jorginho": "jorgeluizmartinsjunior@.com",
    "!ebaych": "ebay.ch",
    "!gday": "Google Past Day",
    "!evri": "Evri",
    "!gkr": "Google KR",
    "!serch": "de.serchilo.net",
    "!ebayca": "ebay.ca",
    "!weboftrust": "Web of Trust",
    "!parking": "ParkWhiz",
    "!pcgw": "PCGamingWiki",
    "!ringtones": "Brinked",
    "!versiontracker": "VersionTracker.com",
    "!truveo": "Truveo",
    "!procog": "ProCog",
    "!startpageimages": "Startpage images",
    "!weatherspark": "Weather Spark",
    "!sfpl": "San Francisco Public Library",
    "!openlibrary": "Open Library",
    "!data": "Infochimps",
    "!duden": "Duden",
    "!rut": "rutracker.org",
    "!newsmax": "NewsMax.com",
    "!esseffr": "ESSEF fr",
    "!infospace": "Infospace",
    "!overstock": "Overstock",
    "!dpts": "Debian Packages",
    "!rtnews": "RT",
    "!xanga": "Xanga",
    "!mefi": "MetaFilter",
    "!salixforums": "SalixOS Forums",
    "!ech": "ebay.ch",
    "!ticketmaster": "Ticket Master",
    "!openstreetmap": "OpenStreetMap",
    "!eca": "ebay.ca",
    "!cercavino": "CercaVino",
    "!quotes": "WikiQuote",
    "!mpl": "matplotlib",
    "!sampled": "whosampled",
    "!caranddriver": "Car and Driver",
    "!distrowatch": "DistroWatch",
    "!metacafe": "Metacafe",
    "!metaso": "Meta Stack Overflow",
    "!macports": "MacPorts",
    "!arstechnica": "ArsTechnica",
    "!pixiv": "Pixiv",
    "!dilbert": "Dilbert",
    "!whatis": "WhatIs.com",
    "!beer": "BeerAdvocate",
    "!exploitdb": "Exploit DB",
    "!scp": "SCP Foundation",
    "!seznam": "Seznam",
    "!pastebin": "pastebin",
    "!rinf": "RINF Alternative news",
    "!ktb": "KDE TechBase",
    "!telegraph": "Telegraph",
    "!seatgeek": "SeatGeek",
    "!newffr": "NewFFR",
    "!gpsies": "GPSies.de",
    "!soundcloud": "SoundCloud",
    "!mediadico": "Mediadico",
    "!csdb": "The C64 Scene Database",
    "!enlt": "Google Translate English to Lithuanian",
    "!chakraforum": "The Chakra Project",
    "!hatesloganmaker": "Sloganmaker /hate",
    "!meteofr": "Météo-France",
    "!wzh": "Wikipedia ZH",
    "!quixey": "Quixey",
    "!123people": "123people",
    "!biblsrv": "Bibleserver",
    "!ap": "AP",
    "!at": "Addictive Tips",
    "!au": "African Unioun",
    "!css": "CSS",
    "!ah": "Así hablamos",
    "!allocine": "Allocine.com",
    "!csw": "Chicken Scheme Wiki",
    "!am": "Amazon.com",
    "!erlang": "Erlang Docs",
    "!chakrapkg": "The Chakra Project Packages",
    "!whu": "Wikipedia Hungary",
    "!themeforest": "ThemeForest",
    "!gamebanana": "GameBanana",
    "!rootsarchives": "Roots Archives",
    "!fileinfo": "File info",
    "!canoo": "canoonet",
    "!autocar": "Autocar.co.uk",
    "!who": "who.is",
    "!about": "About.com",
    "!car": "CarMagazine.co.uk",
    "!whi": "Wikipedia HI",
    "!sqlite": "SQLite",
    "!sm": "Smashing Magazine",
    "!webtender": "Webtender",
    "!so": "StackOverflow",
    "!sh": "SimplyHired",
    "!si": "SI.com",
    "!sk": "songkick.com",
    "!sd": "Slickdeals",
    "!sf": "ServerFault",
    "!gamepro": "GamePro",
    "!studydroid": "StudyDroid",
    "!sc": "Soundcloud",
    "!ccst": "CSS Tricks",
    "!graphemica": "Graphemica",
    "!sx": "stackexchange.com",
    "!liveleak": "http://www.liveleak.com/",
    "!su": "SuperUser",
    "!sv": "La Simpla Vortaro ",
    "!sw": "Simple English Wikipedia",
    "!sp": "StartPage",
    "!mpla": "MenuPages",
    "!sr": "reddit",
    "!ss": "Subscene",
    "!obb": "oremus Bible Browser",
    "!traffic": "Google Traffic",
    "!arturogoga": "Arturogoga",
    "!burnbit": "Burnbit",
    "!gnomebugs": "GNOME Bugzilla",
    "!w3c": "W3C",
    "!clipart": "Microsoft Clipart",
    "!flickrc": "Flickr comm/deriv",
    "!tigerdirect": "TigerDirect",
    "!homedepot": "Home Depot",
    "!mdbg": "MDBG Chinese-English dictionary",
    "!lparchive": "Let's Play Archive",
    "!thesession": "The Session",
    "!nck": "Nciku",
    "!gifl": "Google: I'm Feeling Lucky",
    "!forrst": "Forrst",
    "!trueknowledge": "True Knowledge",
    "!gutenberg": "Project Gutenberg",
    "!susepkg": "openSUSE Software",
    "!cbssports": "CBS Sports",
    "!rlib": "Rapidlibrary",
    "!amf": "Ask Metafilter",
    "!ncz": "Nciku Chinese",
    "!dfman": "DragonFly BSD manual pages",
    "!enpt": "google translate en-pt",
    "!sconj": "SpanishDict verb conjugation",
    "!kicknews": "KickNews",
    "!millionshort": "Million short",
    "!dcc": "dict.cc",
    "!sfgate": "SFGate",
    "!newsweek": "Newsweek",
    "!epicurious": "Epicurious",
    "!archaur": "ArchLinux User Repository",
    "!fsf": "Free Software Foundation",
    "!cafepress": "CafePress",
    "!bizrate": "Bizrate",
    "!gmusic": "Google Music",
    "!sskj": "Slovar slovenskega knjižnega jezika",
    "!color": "0to255.com",
    "!perezhilton": "PerezHilton",
    "!starwars": "Wookiepedia",
    "!macdic": "Macmillan Dictionary",
    "!gtr": "Google TR",
    "!exex": "Experts Exchange",
    "!gtw": "Google TW",
    "!academicearth": "Academic Earth",
    "!gtu": "TechGujarat",
    "!scan": "Scan",
    "!lyricful": "Lyricful",
    "!thesaurus": "Thesaurus.com",
    "!lar": "Larousse Français",
    "!wordnik": "Wordnik",
    "!viul": "Vancouver Island University Library",
    "!mio": "Movies.io",
    "!showtimes": "Google Movies",
    "!steam": "Steam",
    "!biznar": "Biznar",
    "!foolz": "FoOlz [4chan] Archives",
    "!dpv": "Dogpile Video",
    "!dpw": "Dogpile Web",
    "!.net": "DotNet Docs",
    "!wissen": "wissen.de",
    "!viasona": "Viasona",
    "!torrentfreak": "Torrent Freak",
    "!deviantart": "DeviantART",
    "!monster": "Monster.com",
    "!dpd": "Diccionario panhispánico de dudas",
    "!rubydoc": "Ruby-Doc.org",
    "!dpb": "Depiraatbaai",
    "!dpc": "DVDpasCher",
    "!dpl": "Dogpile Local",
    "!dpn": "Dogpile News",
    "!dpi": "Dogpile Images",
    "!spice": "Spiceworks Community",
    "!nokiamaps": "Nokia Maps",
    "!modulusfe": "Modulus Financial Engineering",
    "!archforums": "Arch Linux Forums",
    "!bugmenot": "BugMeNot",
    "!independent": "The Independent",
    "!amiami": "Amiami",
    "!urbancomfort": "Urban Comfort",
    "!ebhk": "ebay.com.hk",
    "!php": "PHP.net",
    "!ncbi": "NCBI",
    "!ninja": "Ninjawords",
    "!mdn": "Mozilla Developer Network",
    "!icheckmovies": "iCheckMovies",
    "!bvideo": "Bing Videos",
    "!smog": "Smogon University",
    "!tubalr": "Tubalr",
    "!tinyurl": "TinyURL.com",
    "!hpv": "Heise.de Preisvergleich",
    "!memoryalpha": "Memory Alpha",
    "!justsnake": "A blog about snakes",
    "!msdn": "MSDN",
    "!download": "Download.com",
    "!chammy": "Chammy.info",
    "!metalarch": "Metal Archives",
    "!tf2": "TF2 Wiki",
    "!earthcam": "earthcam",
    "!wtf": "MirBSD Acronyms Database",
    "!madeinusa": "madeinusa",
    "!oer": "OER Commons",
    "!ausgov": "australia.gov.au",
    "!wtr": "Vikipedi",
    "!dfiles": "Debian file search",
    "!allmovie": "AllMovie",
    "!equestriadaily": "Equestria Daily",
    "!oed": "Oxford English Dictionary",
    "!telefonterror": "Telefonterror",
    "!fedorawiki": "Fedora Project",
    "!dstgb": "StGB - dejure.org",
    "!treccani": "treccani",
    "!tpb": "The Pirate Bay",
    "!sdn": "SAP Developer Network Forums",
    "!youku": "Youku",
    "!ixquick": "ixquick",
    "!dwiki": "Davis Wiki",
    "!yandexmaps": "Yandex Maps",
    "!malist": "MyAnimeList",
    "!mobygames": "Moby Games",
    "!gdocs": "Google Docs",
    "!cached": "Google Cache",
    "!beoes": "Beolingus De-es",
    "!sdz": "Site du Zer0",
    "!root": "ROOT",
    "!shodan": "SHODAN",
    "!viki": "Estonian Wikipedia Vikipeedia",
    "!redtram": "RedTram",
    "!codepoints": "Codepoints",
    "!gmonth": "Google Past Month",
    "!geartested": "GearTested.Net",
    "!unwiki": "Uncyclopedia",
    "!stubhub": "StubHub",
    "!lucire": "Lucire",
    "!technet": "Microsoft TechNet",
    "!tfd": "The Free Dictionary",
    "!finalfantasy": "Final Fantasy Wiki",
    "!market": "Android Market",
    "!gisafeoff": "Google Images Safe Off",
    "!duedil": "Duedil",
    "!faff": "Film Affinity",
    "!globo": "Globo.com",
    "!themoviedb": "TheMovieDB.org",
    "!icm": "iCheckMovies",
    "!wowhead": "WowHead",
    "!bingmaps": "Bing Maps",
    "!chacha": "ChaCha",
    "!evirtau": "Estante Virtual by author",
    "!evirtat": "Estante Virtual by author and/or title",
    "!ede": "ebay.de",
    "!trailer": "Trailer Addict",
    "!gpl": "Google PL",
    "!album": "Allmusic Album Search",
    "!gpe": "Google PE",
    "!gpd": "GoPkgDoc",
    "!yippy": "Yippy",
    "!cpan1": "MetaCPAN",
    "!morningstar": "Morningstar Search",
    "!dilandau": "DilanDau",
    "!thomann": "Thomann",
    "!rseek": "RSeek",
    "!tbuff": "TechnoBuffalo",
    "!ixquickimages": "Ixquick images",
    "!gweek": "Google Past Week",
    "!metacrawler": "MetaCrawler",
    "!derstandard": "derStandard.at",
    "!markos": "markosweb",
    "!cpanm": "MetaCPAN",
    "!coalgirls": "Coalgirls",
    "!kym": "Know Your Meme",
    "!codex": "WordPress Codex",
    "!zuckerzauber": "Caros Zuckerzauber Shop",
    "!userscripts": "UserScripts",
    "!wuk": "Wikipedia UK",
    "!reflets": "Reflets.info",
    "!tripadvisor": "Trip Advisor",
    "!uude": "Ubuntuusers",
    "!wten": "Wiktionary",
    "!tayda": "Tayda Electronics",
    "!kayak": "Kayak",
    "!beo": "Beolingus De-en",
    "!ytw": "Yaoo! Taiwan",
    "!ftube": "FilesTube",
    "!cheatcc": "CheatCC.com",
    "!tunein": "TuneIn",
    "!economist": "The Economist",
    "!keepvid": "KeepVid",
    "!gimages": "Google Images",
    "!meme": "Know Your Meme",
    "!ifdb": "Interactive Fiction Database",
    "!gbang": "GiggleBang",
    "!osmw": "OpenStreetMap Wiki",
    "!ubuntuforums": "Ubuntu Forums",
    "!usatoday": "USA Today",
    "!wtsv": "Wiktionary SV",
    "!glv": "Google LV",
    "!flipkart": "Flipkart",
    "!ehk": "ebay.com.hk",
    "!gturl": "Google Translate URL",
    "!wpt": "Wikipedia PT",
    "!e2": "Everything 2",
    "!win": "Microsoft Windows",
    "!wpp": "WordPress.org Plugins",
    "!roku": "Roku",
    "!gatherer": "Gatherer",
    "!ceneo": "Ceneo",
    "!ka": "Khan Academy",
    "!piratesea": "Pirate Sea",
    "!musipedia": "Musipedia",
    "!puppet": "Puppet Forge",
    "!sxc": "stock.xchng",
    "!eve": "Eve Online",
    "!blendapi": "Blender API",
    "!ks": "KickStarter",
    "!wmeta": "Wikimedia Meta-Wiki",
    "!ad": "Ask Different",
    "!ebuilds": "Gentoo Packages",
    "!eo": "Online Etymology Dictionary",
    "!em": "eBay Motors",
    "!cplusplus": "Cplusplus.com",
    "!d&d": "d20 SRD",
    "!eg": "Epguides",
    "!ed": "Encyclopedia Dramatica",
    "!ee": "ellislab",
    "!eb": "eBay",
    "!ec": "http://ecosia.org/",
    "!quantcast": "Quantcast",
    "!kindle": "Amazon Kindle",
    "!rbugs": "Redhat Bugzilla",
    "!wp7": "Windows Phone 7 Marketplace",
    "!svb": "Silicon Valley Bank",
    "!eqbeats": "Equestrian Beats",
    "!ep": "Experience Project",
    "!startpagevideos": "StartPage videos",
    "!ohlohcode": "Ohloh Code",
    "!fancy": "TheFancy",
    "!mpfl": "MenuPages",
    "!800": "800notes",
    "!foxnews": "FoxNews",
    "!9gag": "9gag",
    "!khronos": "Khronos",
    "!dota": "DOTA 2 wiki",
    "!kazazz": "Kazazz",
    "!nutridata": "nutritiondata",
    "!tproj": "Torrent Project",
    "!monoprice": "Monoprice",
    "!eksisozluk": "Ekşi Sözlük",
    "!sozluk": "Eksi Sozluk",
    "!rpmfind": "RPMfind.net",
    "!planetmc": "Planetminecraft",
    "!encyclopedia": "Wikipedia",
    "!hypestat": "hypestat",
    "!dart": "dartlang",
    "!gametrailers": "Gametrailers",
    "!vs": "Vertical Set",
    "!dictleode": "Leo Translation EN<->DE",
    "!abandonia": "Abandonia",
    "!searchmygmail": "Search My Gmail",
    "!omg": "Jaen",
    "!bliptv": "Blip.tv",
    "!vb": "VedaBase",
    "!clojars": "Clojars",
    "!clker": "Clker",
    "!vg": "Google",
    "!vk": "Vkontakte",
    "!grical": "GriCal",
    "!guitartabs": "GuitarTabsExplorer.com",
    "!netcraft": "Netcraft",
    "!bmp3": "BeeMP3",
    "!mbug": "Mozilla Bugzilla",
    "!dafont": "DaFont",
    "!ecosia": "Ecosia",
    "!expedia": "Expedia",
    "!blekkoi": "blekko.com/ws/ ... /images",
    "!uitinv": "www.uitinvlaanderen.be",
    "!scholarpedia": "Scholarpedia",
    "!zipca": "Zip.ca",
    "!dreamincode": "Dream In Code",
    "!bitgamer": "BitGamer",
    "!make": "Make Magazine Blog",
    "!flashback": "Flashback",
    "!transfermarkt": "transfermarkt.de",
    "!businessweek": "Business Week",
    "!ppa": "Personal Package Archives for Ubuntu",
    "!ppc": "PocketPC.ch",
    "!gigaom": "GigaOM",
    "!gist": "gists.github.com",
    "!npr": "NPR.org",
    "!ipartsplanet": "ipartsplanet.com",
    "!npm": "Node Package Manager",
    "!linuxmint": "Linux Mint Forums",
    "!c2": "C2 Wiki",
    "!willhaben": "Willhaben",
    "!quora": "Quora",
    "!bestbuy": "BestBuy",
    "!graph": "Graph.tk",
    "!digitalcomics": "Digital Comic Museum",
    "!tvcom": "tv.com",
    "!docjar": "Docjar",
    "!dogpile": "Dogpile",
    "!gssl": "Google with SSL",
    "!march": "Metal Archives",
    "!diasporatags": "Diaspora Tags",
    "!popsike": "Popsike",
    "!zoho": "Zoho",
    "!behindthename": "Behind the Name",
    "!metrolyrics": "Metro Lyrics",
    "!gbr": "Google BR",
    "!ebmy": "ebay.com.my",
    "!collaj": "collaj",
    "!operaext": "Opera Extensions",
    "!retailmenot": "RetailgMeNot",
    "!gbe": "Google BE",
    "!gbg": "Google BG",
    "!gbk": "Google Bookmarks",
    "!gbm": "Google Bookmarks",
    "!archiveis": "Archive.is",
    "!coral": "Coral CDN",
    "!vol": "Viva o Linux",
    "!goodfilms": "Goodfil.ms",
    "!appengine": "App Engine Docs",
    "!yubnub": "YubNub",
    "!prfc": "Pretty-RFC",
    "!kpop": "allkpop",
    "!thumbplay": "Thumb Play",
    "!salon": "Salon.com",
    "!dexonline": "Dexonline",
    "!groovy": "Groovy API",
    "!iconfinder": "IconFinder",
    "!dapi": "Drupal API",
    "!grelated": "Google",
    "!newsvine": "Newsvine",
    "!terraria": "Terraria Wiki",
    "!uman": "Ubuntu Manpages",
    "!wtfr": "Wiktionnaire Wiktionary FR",
    "!yui": "YUI Docs",
    "!delluk": "Dell UK",
    "!totalcmd": "TotalCmd.Net",
    "!cstheory": "Theoretical Computer Science - Stack Exchange",
    "!thepiratebay": "The Pirate Bay",
    "!metacpan": "MetaCPAN",
    "!amukmp3": "Amazon.co.uk MP3",
    "!hark": "Hark",
    "!gumtree": "gmtr",
    "!simbad": "SIMBAD Astronomical Database",
    "!ygo": "Yu-Gi-Oh! Wikia",
    "!jf": "JarFinder",
    "!geonames": "GeoNames",
    "!jb": "jupiter broadcasting",
    "!jl": "John Lewis",
    "!irs": "IRS",
    "!selfhtml": "SELFHTML",
    "!tof": "Tree Of Life Web Project",
    "!js": "JavaScript Docs",
    "!jq": "jQuery Docs",
    "!johnlewis": "John Lewis",
    "!irc": "irc.netsplit.de",
    "!lmgtfy": "LMGTFY",
    "!di": "Dictionary.com",
    "!mdc": "Mozilla Developer Center",
    "!dj": "Django documentation",
    "!dm": "Dailymotion",
    "!tweetgrid": "Tweetgrid",
    "!epubbud": "ePub Bud",
    "!da": "DeviantART",
    "!dc": "DuckDuckGo Community Forum",
    "!c1024": "Dem Commander1024 sein Blog",
    "!c1neon": "C1neon",
    "!df": "Daring Fireball",
    "!tf2wiki": "Team Fortress Official Wiki",
    "!dx": "DealExtreme",
    "!sectube": "Security Tube",
    "!dp": "Dogpile",
    "!espn": "ESPN",
    "!librivox": "LibriVox",
    "!kaskus": "Kaskus",
    "!wnetwork": "The Weather Network",
    "!mongo": "MongoDB",
    "!debianfr": "Debian pages in french language",
    "!fedex": "FedEx",
    "!slideshare": "SlideShare",
    "!allrovi": "AllRovi",
    "!boomkat": "boomkat",
    "!modx": "MODX",
    "!atx": "Atomix.vg",
    "!java": "Oracle Java Documentation",
    "!tones": "Thumb Play",
    "!walpha": "WolframAlpha",
    "!enit": "Google translate en-it",
    "!uloz": "uloz.to",
    "!appbrain": "AppBrain",
    "!poetry": "The Poetry Foundation",
    "!thefreedictionary": "The Free Dictionary",
    "!redfin": "RedFin",
    "!symfony": "Symfony Framework",
    "!podnapisi": "Podnapisi",
    "!giez": "Geizhals",
    "!yii": "Yii Framework",
    "!sesli": "Sesli Sözlük",
    "!hackernews": "HNsearch",
    "!youtify": "Youtify",
    "!fbaddons": "Browser Addons: Fireburst",
    "!ticketnetwork": "TicketNetwork",
    "!washingtonpost": "The Washington Post",
    "!desura": "Desura",
    "!graphicriver": "GraphicRiver",
    "!jishoj": "Jisho JAP to ENG",
    "!ebph": "ebay.ph",
    "!ebpl": "ebay.pl",
    "!bvideos": "Bing Videos",
    "!ign": "IGN",
    "!jishoe": "Jisho ENG to JAP",
    "!cisco": "Cisco",
    "!wiktde": "Wiktionary, das freie Wörterbuch",
    "!veekun": "Veekun Pokedex",
    "!geekcafe": "Le geek café",
    "!qomun": "Qomun",
    "!ikeade": "Ikea Germany",
    "!ymovies": "Yahoo! Movies",
    "!unicode": "Unicode Character Search",
    "!epicmafia": "Epic Mafia Wiki",
    "!ebnl": "ebay.nl",
    "!loc": "LOC.gov",
    "!python": "Python Docs",
    "!subscene": "Subscene",
    "!findchips": "FindChips",
    "!qrobei": "qrobe.it Images",
    "!finn": "Finn",
    "!doctrine": "Doctrine ORM",
    "!rottentomatoes": "Rotten Tomatoes",
    "!netzpolitik": "Netzpolitik.org",
    "!t411": "Torrent 411",
    "!synonymes": "Synonymes",
    "!seamonkey": "Seamonkey Add-on",
    "!host": "IP Lookup",
    "!ncheap": "NameCheap",
    "!webcite": "WebCitation",
    "!dbyte": "Darkbyte",
    "!fdroid": "F-Droid",
    "!elibre": "L'étudiant libre",
    "!koders": "Koders",
    "!aops": "Art of Problem Solving Wiki",
    "!play.com": "Play.com",
    "!serverfault": "ServerFault",
    "!emacswiki": "EmacsWiki",
    "!cracked": "Cracked",
    "!freebsdman": "FreeBSD Man Pages",
    "!gcz": "Google CZ",
    "!d20srd": "d20 SRD",
    "!britannica": "Britannica.com",
    "!bol": "Bol.com",
    "!tpbs": "The Pirate Bay sorted by seeds",
    "!gca": "Google CA",
    "!gcn": "Google CN",
    "!gco": "Google CO",
    "!greader": "Google Reader",
    "!adslabs": "NASA ADS Labs",
    "!ghacks": "Ghacks Technology News",
    "!whitepages": "InfoSpace",
    "!christmas": "Find Christmas Presents",
    "!postgresql": "PostgreSQL.org",
    "!photobucket": "PhotoBucket.com",
    "!ordsv": "Ord.se SV",
    "!freitag": "Der Freitag",
    "!jbhifi": "JB-HI-FI",
    "!filmweb": "Filmweb",
    "!ees": "ebay ES",
    "!imslp": "IMSLP",
    "!apple": "Apple",
    "!itunes": "iTunes Apps",
    "!books": "Amazon.com",
    "!ubuntuf": "Ubuntu Forums",
    "!ebaymy": "ebay.com.my",
    "!intaljazeera": "Aljazeera",
    "!gigablast": "GIGABLAST",
    "!blogspot": "Blogspot",
    "!bchain": "blockchain.info",
    "!valleywag": "Valleywag",
    "!whatif": "what if?",
    "!digitalcomicmuseum": "Digital Comic Museum",
    "!booko": "Booko",
    "!8tracks": "8tracks",
    "!naruto": "NarutoPedia",
    "!shodanhq": "SHODAN",
    "!gookokugo": "Goo国語辞典検索",
    "!crawl": "CrawlWiki",
    "!processing": "Processing.org",
    "!guardian": "The Guardian",
    "!nrc": "NRC",
    "!asknews": "Ask News",
    "!ebookee": "Ebookee",
    "!leoe": "LEO Dictionary English",
    "!habbotrading": "Habbo Ruilwaarde",
    "!python30": "Python3.0 Docs",
    "!python31": "Python3.1 Docs",
    "!python32": "Python3.2 Docs",
    "!php2py": "Php2Python",
    "!webstagram": "Webstagram",
    "!diaspora": "Diaspora",
    "!ping": "DomainTools.com",
    "!gph": "Google PH",
    "!parashift": "Parashift.com",
    "!noaa": "NOAA",
    "!fports": "FreeBSD Ports",
    "!discussion": "Google Discussion Search",
    "!artwork": "artcyclopedia.com",
    "!webmenu": "webmenu",
    "!youdao": "Youdao",
    "!eksi": "ek$i sozluk",
    "!otran": "Open-Tran.eu",
    "!entrez": "Entrez",
    "!doaj": "Directory of Open Access Journals",
    "!scribd": "Scribd",
    "!verge": "The Verge",
    "!networkx": "networkx",
    "!songmeaning": "Songmeaning",
    "!markmail": "MarkMail",
    "!gamejaunt": "Game Jaunt",
    "!wp7fr": "Windows Phone 7 Marketplace France",
    "!etym": "etymonline.com",
    "!py3k": "Python 3 docs",
    "!iec": "Institut d'Estudis Catalans",
    "!rswiki": "Runescape Wiki",
    "!archive": "Internet ",
    "!gve": "Google VE",
    "!rlslog": "Releaselog",
    "!gviewer": "Google Docs Viewer",
    "!11870": "11870",
    "!gvn": "Google VN",
    "!geizhals": "Geizhals",
    "!gview": "Google Docs Viewer",
    "!playlist": "Playlist.com",
    "!ebaynl": "ebay.nl",
    "!btcaddr": "blockchain.info",
    "!adsabs": "SAO/NASA Astrophysics Data System",
    "!cartoonnetwork": "Cartoon Network",
    "!anime": "aniDB",
    "!knowyourmeme": "Know Your Meme",
    "!gizoogle": "Gizoogle",
    "!csc": "Chicken Scheme Chickadee",
    "!channel4": "Channel 4",
    "!channel5": "Channel 5",
    "!sheetmusicplus": "Sheet Music Plus",
    "!gyear": "Google Past Year",
    "!tldp": "The Linux Documentation Project",
    "!half": "Half.com",
    "!daum": "Daum",
    "!arch": "ArchLinux Wiki",
    "!splunk": "Splunk",
    "!..": "..duo dotdotduo",
    "!github": "GitHub.com",
    "!lenovo": "Lenovo",
    "!linkup": "LinkUp",
    "!icons": "IconFinder",
    "!tyda": "Tyda.se",
    "!fc": "FreeCode",
    "!fb": "Facebook",
    "!torrent": "ISOHunt",
    "!theh": "the h",
    "!ff": "fanfiction.net",
    "!dkwk": "DokuWiki",
    "!fd": "Free Dictionary",
    "!sourceforge": "SourceForge.net",
    "!bitbucket": "BitBucket.org",
    "!fotolog": "Fotolog",
    "!rae": "Diccionario de la lengua española",
    "!tcl": "TCLers Wiki",
    "!ft": "Financial Times",
    "!bookdepository": "The Book Depository",
    "!fy": "Fuck Yeah",
    "!digg": "Digg",
    "!fsfd": "Free Software Directory",
    "!tigsource": "TIGSource",
    "!bpedia": "Bulbapedia",
    "!audiojungle": "AudioJungle",
    "!pricegrabber": "Price Grabber",
    "!openstreet": "OpenStreetMap",
    "!flex": "Flex Docs",
    "!addic7ed": "Addic7ed",
    "!down": "Down For Everyone Or Just Me",
    "!myfonts": "Myfonts",
    "!dotlan": "Dotlan EVE Maps",
    "!nnd": "Norwegian Nynorsk Dictionary",
    "!heureka": "Heureka!",
    "!vimdoc": "Vimdoc",
    "!pinvoke": "Pinvoke.net",
    "!ehow": "eHow",
    "!matplotlib": "matplotlib",
    "!freedictionary": "Free Dictionary",
    "!nginxwiki": "nginx wiki",
    "!wes": "Wikipedia ES",
    "!weu": "Wikipedia",
    "!ites": "Google translate it-es",
    "!headfi": "Head-Fi",
    "!cve": "Common Vulnerabilities and Exposures CVE",
    "!web": "Web Platform",
    "!fimfic": "FimFiction",
    "!iteo": "Vocabolario Italiano-Esperanto Minnaja",
    "!iten": "Google translate it-en",
    "!gfl": "Google",
    "!2dehands": "2dehands.be",
    "!myanimelist": "MyAnimeList",
    "!wen": "Wikipedia EN",
    "!weo": "Wikipedia EO",
    "!cdt": "China Digital Times",
    "!searchch": "search.ch",
    "!ahk": "AutoHotkey",
    "!dottk": "Dot TK",
    "!imdb": "IMDB",
    "!blindsearch": "Blind Search",
    "!toma": "Toma.hk",
    "!cdc": "CDC",
    "!ahw": "Arkham Horror Wiki",
    "!ebaybe": "ebay.be",
    "!cdn": "Cdn js",
    "!tlfi": "Trésor de la Langue Française informatisé",
    "!pw": "Pricewatch",
    "!wolfram": "WolframAlpha",
    "!ps": "Picsearch",
    "!blocket": "Blocket",
    "!stagevu": "StageVu",
    "!py": "Python Docs",
    "!bsdman": "FreeBSD",
    "!nametoolkit": "NameToolkit",
    "!srfi": "Scheme Request for Implementation",
    "!ifixit": "iFixit",
    "!domain": "NameCheap",
    "!archbugs": "ArchLinux Bugtracker",
    "!pb": "Pinboard",
    "!4sq": "Jaen",
    "!jquery": "jQuery Docs",
    "!tickets": "StubHub",
    "!firefoxmarket": "Firefox Marketplace",
    "!bcwiki": "Bitcoin Wiki",
    "!numpy": "numpy",
    "!srcforge": "SourceForge",
    "!tvguide": "TV Guide",
    "!friendster": "Friendster",
    "!thenation": "The Nation",
    "!eggtimer": "Egg Timer",
    "!911": "911tabs",
    "!dnb": "Deutsche National Bibliothek",
    "!tasteline": "Tasteline",
    "!librarything": "LibraryThing",
    "!forvo": "Forvo",
    "!querycat": "QueryCat",
    "!findjar": "FindJar.com",
    "!dns": "DNS Lookup",
    "!pcpartpicker": "PCPartPicker",
    "!playterm": "PlayTerm",
    "!gw2": "Guild Wars 2 Wiki",
    "!gnews": "Google News",
    "!mtv": "MTV",
    "!arcgisres": "ArcGIS Resource Center",
    "!askubuntu": "Ask Ubuntu",
    "!dw": "Deeper Web",
    "!springsource": "SpringSource",
    "!aliexp": "Aliexpress",
    "!cnbc": "CNBC",
    "!stupi": "Stupidedia",
    "!gae": "Google AE",
    "!bingimages": "Bing Images",
    "!pokepedia": "Pokepedia",
    "!macys": "Macy's",
    "!gat": "Google AT",
    "!gau": "Google AU",
    "!jstor": "JSTOR",
    "!gar": "Google AR",
    "!gas": "Google American Samoa",
    "!2ememain": "2ememain.be",
    "!superd": "SuperDownloads",
    "!gwp": "Google Wikipedia",
    "!wlfind": "cablegatesearch",
    "!ymaps": "Yahoo Maps",
    "!unity": "Unity Answers",
    "!beopt": "Beolingus De-pt",
    "!xkcd": "xkcd",
    "!libuniversitaria": "Libreria Universitaria",
    "!gcl": "Google CL",
    "!allexperts": "All Experts",
    "!adplanner": "Google Ad Planner",
    "!python27": "Python2.7 Docs",
    "!python26": "Python2.6 Docs",
    "!pricespy": "pricespy.co.nz",
    "!zdnet": "ZDNet",
    "!sweetsearch": "SweetSearch4me",
    "!evernote": "Evernote",
    "!appnr": "appnr",
    "!wresfr": "Wordreference",
    "!drinkify": "Drinkify",
    "!marktplaats": "Marktplaats",
    "!gdgt": "gdgt",
    "!distro": "DistroWatch",
    "!okazii": "Okazii",
    "!duck.co": "duck.co",
    "!wired": "Wired",
    "!couponmeup": "CouponMeUp",
    "!zhen": "Nciku",
    "!spezify": "Spezify",
    "!zillow": "Zillow.com",
    "!kotobank": "コトバンク用語検索",
    "!wtde": "Wiktionary Deutsch",
    "!tastekid": "TasteKid",
    "!gopkg": "GoPkgDoc",
    "!gawker": "Gawkr",
    "!googlemap": "Google Maps",
    "!hulu": "Hulu",
    "!wikisimple": "Wikipedia Simple",
    "!oeis": "The On-Line Encyclopedia of Integer Sequences",
    "!veronica": "Veronica2",
    "!blekko": "Blekko",
    "!concerts": "Pollstar",
    "!filecrop": "filecrop",
    "!mtg": "magiccards.info",
    "!sqlalchemy": "SQL Alchemy Docs",
    "!cxx": "Cplusplus.com",
    "!itv": "iTV Player",
    "!tmt": "Tiny Mix Tapes",
    "!tmz": "TMZ",
    "!pcgarage": "pcgarage",
    "!gcal": "Google Calendar",
    "!halopedia": "Halopedia",
    "!readwriteweb": "ReadWriteWeb",
    "!barnesandnoble": "Barnes & Noble",
    "!alexasi": "alexa",
    "!slackbuild": "Slackbuilds",
    "!adlibrisfi": "AdLibris FI",
    "!fcatch": "FileCatch.com",
    "!scopek": "scopek",
    "!uniprot": "uniprot",
    "!superuser": "SuperUser",
    "!dbsnp": "NCBI dbSNP",
    "!thinktutorial": "Th!ink",
    "!evec": "EVE-Central",
    "!pricewatch": "Tweakers Pricewatch",
    "!w3": "W3C",
    "!wfr": "Wikipedia FR",
    "!mouser": "Mouser Electronics",
    "!tvrage": "TVRage",
    "!evirtdes": "Estante Virtual description",
    "!wfa": "Persian Wikipedia",
    "!jms": "JoobMobile Support",
    "!webmd": "WebMD",
    "!wfi": "Finnish Wikipedia",
    "!isitdown": "isup.me",
    "!ieee": "IEEE Xplore Digital Library",
    "!entireweb": "Entireweb",
    "!ada": "Ada 2005 Manual",
    "!collegeboard": "CollegeBoard",
    "!drugbank": "drugbank.ca",
    "!bluray": "blu-ray.com",
    "!ghu": "Google HU",
    "!gwpde": "Google de.Wikipedia",
    "!isbnnu": "isbn.nu",
    "!wikibooks": "Wikibooks",
    "!atomurl": "Atomurl",
    "!wp": "WordPress.org",
    "!wq": "WikiQuote",
    "!wr": "WordReference",
    "!images": "Google Images",
    "!wt": "Wiktionary",
    "!wu": "Weather Underground",
    "!devo": "Dev.Opera ",
    "!menupages": "MenuPages",
    "!psql": "PostgreSQL Docs",
    "!rapgenius": "Rap Genius",
    "!wikihow": "WikiHow",
    "!boingboing": "boingboing",
    "!cppr": "Cppreference",
    "!searchcode": "searchco.de",
    "!wc": "The Weather Channel",
    "!wd": "Website Down",
    "!wf": "fr.wikipedia.org",
    "!wg": "WunderGround",
    "!wm": "Wikipedia mobile",
    "!pitchfork": "Pitchfork Media",
    "!alternative": "AlternativeTo.net",
    "!alexa": "Alexa",
    "!cyberport": "Cyberport",
    "!superdownloads": "SuperDownloads",
    "!craigslist": "Craigslist",
    "!tcgplayer": "TCGPlayer",
    "!tigdb": "The Indie Game Database",
    "!filext": "FILExt",
    "!lwjgl": "LWJGL",
    "!videohive": "VideoHive",
    "!dig": "dig Lookup",
    "!die": "Linux.die.net man pages",
    "!dic": "Dream In Code",
    "!magmawiki": "MagmaWiki",
    "!groklaw": "Groklaw",
    "!wiktbr": "Wikeriadur",
    "!editus": "editus.lu",
    "!adsref": "NASA ADS Bibliographical reference search",
    "!y": "Yahoo!",
    "!pkgsrc": "Pkgsrc.se",
    "!myetym": "www.myetymology.com",
    "!rmp": "Rate My Professor",
    "!emedicine": "Medscape Reference",
    "!gsbr": "Google Shopping BR",
    "!geiz": "Geizhals",
    "!jcpenney": "JC Penney",
    "!lma": "Live Music Archive",
    "!nce": "Nciku English",
    "!heroku": "Heroku Devcenter",
    "!gitl": "Google IT",
    "!bmaps": "Bing Maps",
    "!slbr": "SpeakLikeABrazilian",
    "!rml": "R mailing lists archive",
    "!bandcamp": "Bandcamp",
    "!zerohedge": "ZeroHedge",
    "!gmaps": "Google Maps",
    "!springer": "Springer Link",
    "!sc2ranks": "SC2Ranks",
    "!g4tv": "G4TV",
    "!random": "random.org",
    "!like": "Thesaurus.com",
    "!emule": "eMule Content Database",
    "!tr": "Google Translate",
    "!punchfork": "Punchfork",
    "!niv": "BibleStudyTools.com",
    "!thetvdb": "The TV db",
    "!yaen": "Yandex",
    "!essefn": "ESSEF nl",
    "!nih": "NIH",
    "!metal": "Encyclopedia Metallum The Metal Archives",
    "!glink": "Google",
    "!shbd": "Shabdkosh",
    "!wikide": "Wikipedia",
    "!fgf": "Flightgear Forums",
    "!lisp": "Lispdoc",
    "!downfor": "DownForEveryone?",
    "!asn": "AS Lookup",
    "!ask": "Ask.com",
    "!ujc": "Internetová jazyková příručka",
    "!archpkg": "ArchLinux Packages",
    "!hes": "HES Data Dictionary",
    "!tinypic": "TinyPic",
    "!evirt": "Estante Virtual all",
    "!wwend": "Worlds Without End",
    "!artist": "artcyclopedia.com",
    "!amo": "Firefox Addons",
    "!aes": "Amazon ES",
    "!adobe": "Adobe",
    "!archwiki": "ArchLinux Wiki",
    "!subito": "Subito.it",
    "!furet": "Furet du Nord",
    "!jalopnik": "Jalopnik",
    "!wordreference": "WordReference",
    "!ohloh": "ohloh",
    "!filestube": "FilesTube",
    "!myspace": "MySpace",
    "!kickasstorrents": "Kick Ass Torrents",
    "!build": "Build.com",
    "!jeux": "JeuxVideo",
    "!gtfr": "Google Translate to French",
    "!moddb": "ModDB",
    "!datpiff": "Datpiff",
    "!mcskin": "Minecraft Skin Search",
    "!as3": "AS3 Docs",
    "!spanishdict": "SpanishDict",
    "!softpedia": "Softpedia",
    "!yahoo": "Yahoo!",
    "!drupal": "Drupal",
    "!safebooru": "Safebooru",
    "!mercadolibre": "Mercado Libre",
    "!rollingstone": "Rolling Stone",
    "!viewpdf": "Online PDF Viewer",
    "!wallpaper": "Google Images",
    "!grooveshark": "Grooveshark",
    "!netgear": "Netgear",
    "!bsd": "GoogleBSD",
    "!wiktfr": "Wiktionnaire",
    "!webwarper": "WebWarper.com",
    "!ikeafr": "Ikea FR",
    "!sumotorrent": "sumotorrent",
    "!railsdock": "Rails-Dock",
    "!dtdeals": "DoubleTakeDeals",
    "!omgu": "OMG! Ubuntu!",
    "!btabs": "UltimateGuitar.com",
    "!diccionari": "Diccionari de la llengua Catalana",
    "!usaspending": "usaspending.gov",
    "!evewiki": "EVElopedia",
    "!puc": "Ubuntu Packages Search",
    "!ral": "RAL color coding system",
    "!hymnary": "Hymnary",
    "!mimvi": "Mimvi",
    "!lmddgtfy": "LMDDGTFY.NET",
    "!versandapo": "VersandApo",
    "!kprojects": "KDE Git Projects",
    "!howtogeek": "How-To Geek",
    "!metalab": "Metalab Mediawiki",
    "!userstyles": "Userstyles",
    "!opera": "Opera Extension",
    "!file": "FileHippo",
    "!gems": "RubyGems",
    "!etsy": "Etsy",
    "!ext": "FILExt",
    "!applediscuss": "Apple Discussions",
    "!ios": "iOS Developer Library",
    "!linuxhcl": "Linux Hardware Compatibility List",
    "!esit": "Google translate es-it",
    "!lasership": "LaserShip",
    "!abcnotation": "abcnotation.com",
    "!iol": "IOL",
    "!evirted": "Estante Virtual by publisher",
    "!cultureunplugged": "CultureUnplugged.com",
    "!snl": "http://snl.no/",
    "!ctan": "CTAN.org",
    "!sporcle": "Sporcle",
    "!kol": "The KoLwiki",
    "!amazonfr": "Amazon france",
    "!pbs": "PBS",
    "!xiami": "Xiami",
    "!port": "port Lookup",
    "!ebayhk": "ebay.com.hk",
    "!scirus": "Scirus",
    "!pbi": "Pbi Directory",
    "!hackage": "HackageDB",
    "!comicrocket": "Comic Rocket",
    "!kos": "KingOfSat",
    "!opensubtitles": "OpenSubtitles.org",
    "!verticalset": "Vertical Set",
    "!dribble": "dribbble",
    "!oracle": "Oracle.com",
    "!metafilter": "MetaFilter",
    "!ordnet.dk": "Ordnet",
    "!bookfinder": "Book Finder",
    "!register": "The Register",
    "!firmycz": "firmy.cz",
    "!yandexm": "Yandex Market",
    "!pic": "picsearch",
    "!reuters": "Reuters",
    "!cpan": "MetaCPAN",
    "!tvlinks": "TVLinks",
    "!hitchwiki": "Hitchwiki",
    "!wtit": "Wiktionary",
    "!dash": "Digital Access to Scholarship at Harvard",
    "!wpthemes": "WordPress.org Themes",
    "!jarvanaproject": "Jarvana",
    "!cpap": "CPAP.com",
    "!habr": "HabraHabr",
    "!local": "Google Local",
    "!ames": "Amazon España",
    "!uschess": "US Chess Federation",
    "!mathworld": "Wolfram MathWorld",
    "!gcache": "Google Cache",
    "!isbndb": "ISBNdb.com",
    "!brreg": "Brønnøysundregistrene",
    "!academic": "Microsoft Academic",
    "!bookflavor": "Bookflavor",
    "!citeul": "CikeULike",
    "!aion": "Aion Wiki",
    "!ox": "Oxford Dictionaries",
    "!oz": "Stichting OZNB Foundation",
    "!nndb": "NNDB",
    "!nolo": "Nolo.com",
    "!gcode": "Google Code",
    "!reed": "reed.co.uk",
    "!genesis": "Library Genesis",
    "!yr": "yr",
    "!identica": "Identi.ca",
    "!lynx": "lynx.io",
    "!progarchives": "Prog Archives",
    "!qrz": "QRZ.com",
    "!shoutitout": "Shoutitout",
    "!cine": "Cinemassacre",
    "!yc": "HNsearch",
    "!mkz": "musik",
    "!wbr": "Wikipedia Brezhoneg",
    "!yf": "Yahoo Finance",
    "!asksutra": "Ask Sutra",
    "!codecanyon": "CodeCanyon",
    "!osi": "Open Source Initiative",
    "!arduino": "Arduino",
    "!ose": "Open Site Explorer",
    "!track": "PackageMapping",
    "!mpbo": "MenuPages",
    "!pond5": "Pond5",
    "!chilango": "Chilango",
    "!nina": "Narodowy Instytut Audiowizualny nina.gov.pl",
    "!similarsitesearch": "similarsitesearch",
    "!gshopping": "Google Shopping",
    "!ohinternet": "ohinternet.com",
    "!smashwords": "Smashwords",
    "!fullwiki": "The Full Wiki",
    "!tvdb": "TheTVDB.com",
    "!apidockruby": "APIdock",
    "!abe": "Abe's Market",
    "!video": "YouTube",
    "!dfwiki": "DwarfFortress Wiki",
    "!google": "Google",
    "!linkscape": "Open Site Explorer",
    "!thwiki": "Touhouwiki English",
    "!digikey": "Digi-Key",
    "!gfinance": "Google Finance",
    "!smallsafari": "SmallSafari",
    "!ultimateguitar": "Ultimate Guitar",
    "!dirae": "Dirae",
    "!techiris": "The TechIRIS",
    "!clusty": "Clusty",
    "!latimes": "LATimes",
    "!dhlde": "DHL German",
    "!besch": "Bescherelle",
    "!gamerankings": "GameRankings.com",
    "!staples": "Staples.com",
    "!fnac": "Fnac",
    "!malpha": "Memory Alpha",
    "!australian": "The Australian",
    "!paleo": "Paleo Hacks",
    "!danbooru": "Danbooru",
    "!ebsg": "ebay.com.sg",
    "!packagist": "Packagist",
    "!software": "Download.com",
    "!jigsaw": "Jigsaw",
    "!msnbc": "MSNBC",
    "!squidoo": "Squidoo",
    "!adlibrisse": "AdLibris SE",
    "!ddo": "Den Danske Ordbog",
    "!phpnet": "PHP.net",
    "!nzb": "NzbMatrix",
    "!ddg": "DuckDuckGo",
    "!scripts": "HotScripts",
    "!ebayfr": "ebay.fr",
    "!howtoforge": "HowtoForge",
    "!webischool.org": "webischool.org",
    "!cpuworld": "cpu-world.com",
    "!theonion": "The Onion",
    "!ebay": "eBay",
    "!kat": "Kick Ass Torrents",
    "!seeks": "Seeks",
    "!quran": "The Noble Qur'an",
    "!yv": "Yahoo",
    "!drive": "Google Drive",
    "!ptp": "Pass The Popcorn",
    "!ebat": "ebay.at",
    "!infochimps": "Infochimps",
    "!jalop": "Jalopnik",
    "!gth": "Google TH",
    "!buej": "BU Alumni Medical Library- E-Journals",
    "!appleinsider": "AppleInsider",
    "!woxikon": "Woxikon",
    "!node": "node.js docs",
    "!weatherbug": "WeatherBug",
    "!zahe": "Zahe.me",
    "!macaddress": "MAC Address",
    "!rdio": "Rdio",
    "!nettuts": "Nettuts+",
    "!tawlk": "Tawlk",
    "!vala": "http://live.gnome.org/Vala",
    "!csmonitor": "CSMonitor",
    "!hphys": "HyperPhysics",
    "!searchcpan": "CPAN",
    "!recipes": "Punchfork",
    "!dtag": "DebTags",
    "!mspawiki": "MS Paint Adventures Wiki",
    "!enl": "ebay.nl",
    "!dpr": "dpreview",
    "!gnz": "Google New Zealand",
    "!gnu": "GNU",
    "!freedict": "Free Dictionary",
    "!opencv": "OpenCV documentation",
    "!l1sp": "Lisp Docs",
    "!gnm": "Google News mobile",
    "!gnl": "Google NL",
    "!gno": "Google NO",
    "!osm": "OpenStreetMap",
    "!translate": "Google Translate",
    "!developpez": "Developpez.com",
    "!orielly": "O'Reilly",
    "!wresen": "WordReference",
    "!ens": "Ensembl",
    "!trisquel": "Trisquel",
    "!dsd": "Den Store Danske",
    "!eff": "Electronic Frontier Foundation",
    "!yt": "YouTube",
    "!isgd": "is.gd",
    "!digitalspy": "DigitalSpy",
    "!gamecheats": "CheatCC",
    "!allmusic": "AllMusic",
    "!name": "Name.com ",
    "!unix": "The Unix Tree",
    "!savannah": "Savannah",
    "!use": "Unix & Linux StackExchange",
    "!dmoz": "dmoz",
    "!allposters": "All Posters",
    "!perlmod": "p3rl.org",
    "!sigma": "Sigma Aldritch Catalog",
    "!greeksubtitles": "Greek Subtitles Project",
    "!h33t": "h33t",
    "!fool": "Fool.com",
    "!sapo": "SAPO",
    "!fonplus": "Find People on Plus",
    "!zemljevid": "Zemljevid Najdi.si",
    "!amde": "Amazon.de",
    "!dplb": "DPLB",
    "!watch": "YouTube",
    "!synonyms": "Thesaurus.com",
    "!drupalapi": "Drupal API",
    "!french": "French Language and Usage",
    "!stabs": "Songsterr",
    "!jamendo": "Jamendo",
    "!costco": "Costco.com",
    "!nf": "netflix",
    "!ne": "Newegg",
    "!nx": "networkx",
    "!kelkoo": "Kelkoo UK",
    "!stumbleupon": "StumbleUpon",
    "!gmg": "Green Man Gaming",
    "!godaddy": "GoDaddy",
    "!efr": "ebay.fr",
    "!wca": "Wikipedia CA",
    "!cultofmac": "Cult of Mac",
    "!kong": "Kongregate",
    "!mywot": "Web of Trust",
    "!wcs": "Wikipedia Cs",
    "!mafia": "mafiatoday",
    "!safeon": "DDG Safesearch On",
    "!head-fi": "Head-Fi",
    "!mpch": "MenuPages",
    "!guildwiki": "Guild Wiki",
    "!osvdb": "The Open Source Vulnerability Database",
    "!redz": "RedZ",
    "!wwwjdic": "WWWJDIC",
    "!fotobanka": "FotoBanka",
    "!corriere": "Corriere della Sera",
    "!furaffinity": "FurAffinity",
    "!readthedocs": "Read the Docs",
    "!ponsde": "PONS",
    "!mmls": "Minuteman Library Network",
    "!enes": "Google translate en-es",
    "!ubuntuusers": "Ubuntuusers",
    "!enel": "Google translate en-el",
    "!eneo": "Sonja's English-Esperanto Dictionary",
    "!biblegateway": "BibleGateway",
    "!mysql": "MySQL.com",
    "!perl": "p3rl.org",
    "!nhl": "NHL.com",
    "!wrfe": "Wordreference fr->en",
    "!ukp": "UK Parliament",
    "!shelfari": "Shelfari",
    "!mapquest": "Mapquest",
    "!ffm": "Firefox Marketplace",
    "!touhou": "Touhou Wiki",
    "!elexikon": "Elektronik-Lexikon",
    "!gmail": "GMail.com",
    "!mill": "Million short",
    "!jpg": "http://jpg.to/",
    "!amcn": "Amazon.cn",
    "!wru": "Wikipedia RU",
    "!chow": "Chowhound",
    "!amca": "Amazon.ca",
    "!mozbrowser": "MozBrowser.nl",
    "!wayback": "Wayback Machine",
    "!imdbp": "IMDB pro",
    "!jar": "FindJar.com",
    "!folktunefinder": "FolkTuneFinder",
    "!robtex": "Robtex",
    "!esen": "Google translate es-en",
    "!slickdeals": "SlickDeals",
    "!movieweb": "Movie Web",
    "!batoto": "Batoto",
    "!miniinthebox": "MiniInTeBox",
    "!feedbooks": "Feedbooks",
    "!tnw": "The Next Web",
    "!tnt": "TNT",
    "!oca": "Open Clip Art Library",
    "!pspgen": "PSP GEN",
    "!is": "http://ilmainensanakirja.fi/",
    "!pten": "Google Translate pt-en",
    "!iso": "DistroWatch",
    "!iw": "InstantWatcher",
    "!ocw": "MIT OpenCourseWare",
    "!ix": "Ixquick Alias",
    "!fowiki": "The Vault/Nukapedia/Fallout Wiki",
    "!aljazeera": "Aljazeera English",
    "!bangs": "DuckDuckGo",
    "!charitynavigator": "Charity Navigator",
    "!qtc": "Nokia QT Docs",
    "!simplyhired": "SimplyHired",
    "!multicolr": "Multicolr Search Lab",
    "!gse": "Google SE",
    "!ebuild": "Gentoo Packages",
    "!dispt": "Dispostable",
    "!poems": "The Poetry Foundation",
    "!eow": "英辞郎 on the WEB Pro",
    "!amazon": "Amazon.com",
    "!mpdc": "MenuPages",
    "!uitm": "Uitmuntend",
    "!gsa": "GSA Advantage",
    "!localch": "local.ch",
    "!thefutoncritic": "The Futon Critic",
    "!cran": "CRAN",
    "!flattr": "Flattr",
    "!goear": "Goear",
    "!awimg": "All the web, yahoo version",
    "!pythondev": "Python dev doc",
    "!delicious": "delicious",
    "!wikinews": "Wikinews",
    "!albumartcd": "Albumart Music",
    "!ya": "Yandex",
    "!tivo": "TiVo",
    "!selfhtmlwiki": "SELFHTML wiki",
    "!othes": "http://openthes-es.berlios.de/",
    "!sos": "Software OpenSuse",
    "!docubufr": "Documentation Ubuntu-fr",
    "!ciu": "Can I use...",
    "!auk": "Amazon UK",
    "!slatefr": "Slate.fr",
    "!brew": "Homebrew",
    "!aur": "Arch Linux",
    "!cia": "CIA World Factbook",
    "!snuson": "SnusOn",
    "!gblogs": "Google Blogs",
    "!hn": "HNsearch",
    "!ikea": "Ikea",
    "!edgar": "EDGAR",
    "!ck12": "cK-12.org",
    "!linuxfr": "LinuxFr.org",
    "!mightyape": "Mighty Ape",
    "!vimeo": "Vimeo",
    "!fox": "Fox News",
    "!altto": "AlternativeTo",
    "!gtde": "Google Translate to German",
    "!octopart": "Octopart",
    "!creativecowlib": "Creative Cow Library",
    "!blueletterbible": "Blue Letter Bible",
    "!fbrecipes": "Recipes: Fireburst",
    "!uu": "Ubuntuusers",
    "!commons": "Wikimedia Commons",
    "!rubygems": "RubyGems",
    "!bitesizegcse": "BBC GCSE Bitesize",
    "!x86": "x86 Opcode & Instruction Reference",
    "!ug": "Ultimate Guitar",
    "!ud": "Urban Dictionary",
    "!django": "Django Docs",
    "!maany": "Almaany",
    "!xmarks": "Xmarks | Boomark Sync and Search",
    "!freshports": "FreshPorts",
    "!lnu": "Library.nu",
    "!ftram": "File Tram",
    "!zvon": "ZVON.org",
    "!playasia": "Play-asia",
    "!iops": "Iops",
    "!pminister": "Priceminister",
    "!rbl": "RBL Lookup",
    "!gscholar": "Google Scholar",
    "!acronym": "Acronyms",
    "!piratebay": "The Pirate Bay",
    "!som": "Spirit of Metal",
    "!ktechbase": "KDE TechBase",
    "!lonelyplanet": "lonelyplanet",
    "!braumeister": "Braumeister",
    "!vossey": "Vossey.com",
    "!arxiv": "arXiv",
    "!metacritic": "Metacritic",
    "!lyriki": "Lyriki",
    "!blinders": "DuckDuckGo Blinders",
    "!tineye": "Tineye",
    "!rdoc": "RubyDoc.info",
    "!yelp": "Yelp",
    "!jeuxvideo.com": "jeuxvideo.com",
    "!./": "Slashdot",
    "!djangome": "Django Docs",
    "!etymology": "EtymOnline.com",
    "!pipl": "Pipl",
    "!parlysearch": "ParlySearch",
    "!baixaki": "Baixaki",
    "!instructables ": "Instructables",
    "!glt": "Google LT",
    "!ruby": "Ruby-lang.org",
    "!techjungle": "Tech Jungle",
    "!ebayit": "ebay.it",
    "!bnews": "Bing News",
    "!bnf": "Bibliothèque nationale de France ",
    "!gulesider": "Gule Sider",
    "!newyorker": "The New Yorker",
    "!wikit": "Wikitravel",
    "!jisho": "Jisho",
    "!portableapps": "PortableApps.com",
    "!smogon": "Smogon University",
    "!punguzo": "Punguzo.com",
    "!apertium": "Appertium",
    "!twitter": "Twitter",
    "!omq": "Open.MapQuest.com",
    "!wikic": "Wikimedia Commons",
    "!wikia": "Wikia",
    "!netflix": "Netflix current one is broken",
    "!pinterest": "pinterest.com/",
    "!recycle": "Earth911.com",
    "!repubblica": "la Repubblica",
    "!gri": "Google Reverse Image Search",
    "!courant": "Hartford Courant",
    "!cooksi": "Cook's Illustrated",
    "!gro": "Google RO",
    "!posix": "The Open Group",
    "!minecraft": "Minecraft Wiki",
    "!gru": "Google RU",
    "!grv": "Grooveshark",
    "!flickr": "Flickr",
    "!xing": "Xing.de",
    "!fssc": "Code: Fireburst Specialized Search",
    "!safeoff": "Safe search off",
    "!usps": "USPS",
    "!stumble": "StumbleUpon",
    "!pyramid": "Pyramid Web Application Development Framework",
    "!stuffnz": "stuff.co.nz",
    "!amuk": "Amazon.co.uk",
    "!alternativeto": "AlternativeTo",
    "!pandora": "Pandora",
    "!hitta": "Hitta",
    "!cspan": "C-SPAN",
    "!gratefuldead": "Grateful Dead Concerts",
    "!qur": "The Noble Qur'an",
    "!seslisozluk": "sesli sözlük",
    "!vagalume": "Vagalume",
    "!ricardo": "www.ricardo.ch",
    "!mapsfr": "Google Maps FR",
    "!swipl": "SWI-Prolog",
    "!basesearch": "BASE Bielefeld Academic Search Engine",
    "!eu3": "Europa Universalis III Wiki",
    "!zf": "http://framework.zend.com",
    "!rom": "Emuparadise",
    "!kolw": "Kingdom of Loathing Wiki",
    "!cheatcodes": "CheatCC",
    "!ovi": "Ovi Store",
    "!mbsdman": "MirBSD Manpages",
    "!ord": "Ord.se",
    "!flix": "http://www.flixster.com/",
    "!roto": "Rotoworld",
    "!hayoo": "Hayoo",
    "!kuler": "Adobe Kuler",
    "!jaba": "JABA and JEAB articles",
    "!image": "Google Images",
    "!niif": "NIIF Institute",
    "!microsoft": "Microsoft",
    "!geegain": "Geegain Search",
    "!tpp": "ThePirateParty TPB Mirror",
    "!dict": "DICT.org",
    "!tknowledge": "True Knowledge",
    "!jobs": "Indeed",
    "!gza": "Google ZA",
    "!allrecipes": "All Recipes",
    "!rogerebert": "Roger Ebert",
    "!redflagdeals": "RedFlagDeals.com",
    "!dpackages": "Debian Packages",
    "!greplin": "Greplin",
    "!gephi": "Gephi",
    "!debml": "Debian Mailing Lists",
    "!dealextreme": "DealExtreme",
    "!tgdict": "tangorin",
    "!dpkg": "Debian Packages",
    "!archived": "Wayback Machine",
    "!ark": "Intel Ark",
    "!occuprint": "Occuprint",
    "!ars": "Ars Technica",
    "!gban": "GameBanana",
    "!emag": "eMAG",
    "!locita": "Locita",
    "!homebase": "Homebase",
    "!adn": "app.net",
    "!sitealytics": "sitealytics.com",
    "!darklyrics": "DarkLyrics.com",
    "!grepcpan": "CPAN -> GREP",
    "!mashable": "Mashable",
    "!adc": "Apple Developer Center",
    "!torrentz": "Torrentz",
    "!posten": "Posten",
    "!osxdaily": "Osxdaily",
    "!vgmdb": "VGMdb",
    "!ads": "SAO/NASA ADS",
    "!shop": "Yahoo! Shopping",
    "!kobo": "Kobo",
    "!dlss": "Summon Duke",
    "!tz": "timeanddate",
    "!peppermintos": "Peppermint OS forums",
    "!slyrics": "SONG LYRICS",
    "!patft": "US Patent Database Search",
    "!tt": "Tokyo Toshokan",
    "!tw": "Twitter",
    "!tv": "Yahoo! TV",
    "!javascript": "JavaScript Docs",
    "!tk": "True Knowledge",
    "!slackfind": "Slackfind",
    "!vatera": "Vatera",
    "!imeem": "Imeem",
    "!tc": "Techcrunch",
    "!buscape": "Buscapé",
    "!tg": "ThinkGeek",
    "!wikipainting": "wikipaintings",
    "!mydealz": "myDealZ",
    "!tmark": "Justia.com trademarks",
    "!watchanime": "Watch Anime On",
    "!vbox7": "Vbox7",
    "!tanka": "Tankafetast",
    "!pyside": "PySide",
    "!maxthon": "Maxthon 3 Extension",
    "!ufrj": "Universidade Federal do Rio de Janeiro",
    "!francesurf": "FranceSurf",
    "!urban": "Urban Dictionary",
    "!anagram": "One Across",
    "!proofwiki": "ProofWiki",
    "!omgubuntu": "OMG! Ubuntu!",
    "!pypi": "Pypi.python.org",
    "!d20pfsrd": "Pathfinder SRD",
    "!lxr": "Linux Cross Reference",
    "!fsfe": "Free Software Foundation Europe",
    "!wiktes": "Wikcionario",
    "!redbox": "RedBox",
    "!dbugs": "Debian Bugs",
    "!nbsdman": "NetBSD manual pages",
    "!rso": "R questions on Stack Overflow",
    "!clubic": "Clubic",
    "!karmadecay": "Karma Decay",
    "!gethuman": "GetHuman",
    "!openprocessing": "OpenProcessing",
    "!cocoa": "Apple Developer",
    "!rdns": "Reverse DNS",
    "!liberia": "Libreria Universitaria",
    "!gmx": "Google MX",
    "!gmy": "Google MY",
    "!ein": "ebay.in",
    "!thestar": "The Star",
    "!demonoid": "Demonoid",
    "!erowid": "Erowid",
    "!eie": "ebay.ie",
    "!hastane": "Hastane",
    "!shutterstock": "Shutterstock",
    "!eit": "ebay.it",
    "!mc": "Metacritic",
    "!wetter": "Wetter.com",
    "!peeron": "Peeron",
    "!smh": "SMH.com.au",
    "!smg": "Search My Gmail",
    "!start": "START",
    "!golang": "Go Programming Language",
    "!edgart": "Edgar",
    "!onr": "Oh No Robot",
    "!ficly": "ficly",
    "!rs4": "rs.4chan.org",
    "!argos": "Argos",
    "!gsg": "Google SG",
    "!speed": "Speed.cd",
    "!gsc": "Google Scholar",
    "!khan": "Khan Academic",
    "!elreg": "The Register",
    "!gsl": "Google SL",
    "!gsk": "Google SK",
    "!mediawiki": "MediaWiki",
    "!openports": "OpenPorts",
    "!bacon": "Oracle of Bacon",
    "!raamattu": "Koivuniemen Raamattuhaku",
    "!pci": "http://www.pcinpact.com",
    "!googleimages": "Google Images",
    "!uncyclopedia": "Uncyclopedia",
    "!howstuffworks": "How Stuff Works",
    "!wolframalpha": "WolframAlpha",
    "!circuitcity": "Circuit City",
    "!esvonline": "ESVonline",
    "!bulba": "Bulbapedia",
    "!findlunchin": "FindLunchIn",
    "!scrabblelookup": "scrabblelookup",
    "!ipt": "IP Torrents",
    "!filehippo": "FileHippo",
    "!urbandictionary": "Urban Dictionary",
    "!ptv": "PipocasTV",
    "!mcwiki": "Minecraft Wiki",
    "!wikipaintings": "wikipaintings",
    "!theregister": "the register",
    "!ebau": "ebay.com.au",
    "!linguee": "Linguee",
    "!disney": "Disney.com",
    "!waffles": "Waffles",
    "!wpplugins": "WordPress.org Plugins",
    "!airbnb": "airbnb",
    "!walmart": "WalMart",
    "!longurl": "LongURL.org",
    "!iafd": "internet adult film database",
    "!salix": "SalixOS",
    "!wsv": "Wikipedia SV",
    "!activestate": "ActiveState.com",
    "!scholar": "Google Scholar",
    "!wsl": "Wikipedia SL",
    "!bbcfood": "BBC Food",
    "!wsj": "The Wall Street Journal",
    "!norsk": "Norskordbok | UiO",
    "!nicolinux": "Le blog de Nicolinux",
    "!openbsd": "OpenBSD",
    "!magiccards": "Magiccards.info",
    "!euk": "ebay.co.uk",
    "!tig": "TIGSource",
    "!hp": "HP",
    "!kcls": "King County Library System"
}
